### ISSUE TITLE
"Webpage is slowing down your browser" warning pops in Firefox after installation of the plugin

### ISSUE THREAD

**Issue by w7089** [hyyan/woo-poly-integration#123]
Hi, 
It happens when i edit any product. After the warning i can do nothing, but stop editing.
My wordpress is 4.7 and latest version of Polylang
Can you advise?
Thanks in advance.

**Comment by Jon007** [comment]
Hi, there's not normally any problem like this, maybe there is something else in the theme or another plugin which is conflicting?
Also a wrongly configured Wordpress can get into infinite redirect loops which can upset the browser, in that case though the problem could occur without wooCommerce.

Can you confirm:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

#### What are product versions and settings are you using when this issue occurs?  eg:
* WordPress: 
* WooCommerce: 
* Polylang: 
* Hyyan WooCommerce Polylang Integration: 
* Firefox:

**Comment by Jon007** [comment]
I agree that product editing is heavy-duty on the pc, especially if you have image galleries and other plugins extending the product user interface.
However I'm not convinced that this plugin makes the situation any worse.  The plugin mostly operates at the server end, it's not increasing the client payload in any significant way.

All I can suggest is use the screen options box at the top to turn off any boxes you don't need while you are doing the translations, this will reduce the overall screen payload.

For example if just translating descriptions and titles, then you can turn off the product image, gallery and even product data section to have quicker loading pages.  Whereas if everything is turned on, including Comments, and sections from other tools then it's going to be slower.

**Comment by Jon007** [comment]
I'm reopening with more comments and ideas.

Fields locker code is unoptimised currently: if Meta synchronising is all enabled it's calling JQuery 62 times with a general selectors list.
On a MacBook pro, this takes about 900ms, a fix in testing reduces this to around 120ms.  On a slower computer this could be taking a few seconds at the moment.  
Due to the WordPress Heartbeat, this code is rerun every few seconds...  which if it takes a few seconds to run, means the system may be permanently busy.

Try this:
- **turn off the Fields locker**:  go to Settings, WooPoly, /wp-admin/options-general.php?page=hyyan-wpi and uncheck the Fields Locker and Save.


Additional recommendations for slow computer:

- Use Screen Options to turn off boxes that you don't need on the product edit screen
- Reduce Autosave frequency, eg add in wp-config.php
```
/* switch autosave to 10 minutes */
define('AUTOSAVE_INTERVAL', 600);
```
or as appropriate for your situation.
