### ISSUE TITLE
Errors when do not sync some product attributes

### ISSUE THREAD

**Issue by FidlaFidla** [hyyan/woo-poly-integration#124]
I need for tax and price not to be synchronized. After I unchecked this in plugin settings,  I get many warnings like this:

Warning: array_merge(): Argument #2 is not an array in .../wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Meta.php on line 268

Warning: in_array() expects parameter 2 to be array, null given in .../wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Meta.php on line 291

Why?

**Comment by Jon007** [comment]
Which versions are you using for this?
That sounds like a wooCommerce 3.x issue.

If so, it is fixed in pull request 0.30RC1, the code is available at:
https://github.com/Jon007/woo-poly-integration/releases

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.

**Comment by hyyan** [comment]
Closing the issue, as this must solve in version 1.0.0
@FidlaFidla please feel free to re-open if this is still an issue
