### ISSUE TITLE
Cart, account, checkout do not redirect to the right language

### ISSUE THREAD

**Issue by marinaferracane** [hyyan/woo-poly-integration#126]
Hello, I'm writing as I have an issue with the integration on the second language to my eshop.
I have the woocommerce and installed the polylang. 
Then I have also installed teh woo-poly-integration and added the new pages (cart, checkout, account..) in the second language. The problem is when I 'm on the second language version ( english) and click on "account " or just add a product on the and going to the checkout, this redirect to the primary language (french).

Would you please advise what's i do wrong?

Kind regards, 
Marina

**Comment by Lauriy** [comment]
I seem to have a similar problem after a Wordpress auto-update.

https://altan.ee <- default language should be Estonian.
Clicking on any main menu items will switch back to English.

**Comment by Jon007** [comment]
Hi, although there are several possible configuration errors that could lead to this type of situation:

1. the menu is simply set up wrong:  you should have a separate menu for each language which should link to the relevant language pages
1. some conflict between .htaccess, theme and permalink settings
1. If it's the language switcher itself that is going to the home page of the other language instead of the translated page, then the linked translations are not connected.

If it's not that, check it's not a theme or plugin conflict:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: 
* Hyyan WooCommerce Polylang Integration: 
* Browser:

**Comment by Lauriy** [comment]
Did a revert to the automatic update and it seemed to solve the problem.

**Comment by Jon007** [comment]
ok good, but be careful, don't automatically update to WooCommerce 3.0.x yet!
There are quite a few changes and a related pull request under review on this project.
