### ISSUE TITLE
Still can't translate variations description

### ISSUE THREAD

**Issue by StarStep** [hyyan/woo-poly-integration#128]
I was unable to translate product description because it was disabled, so i updated:

`$selectors[] = '#variable_product_options :input`
with
`$selectors[] = '#variable_product_options :input:not([name^="variable_description"])';`

inside **Variable.php**, function : **extendFieldsLockerSelectors()**

Now it seems to work. Is that right?

**Comment by Jon007** [comment]
I agree, your proposed change tests out ok with me.

I was just looking at the fix "Fix variation description couldnt be translated"
https://github.com/hyyan/woo-poly-integration/pull/87/commits/c012a007e0fb7cba2e92b5dc4db9ef2489741c19
Actually v0.29.1 fix does not allow the variation description to be translated due to the fields locker.

Your fix addresses that.

**Comment by Jon007** [comment]
Fix included in pull request 0.30RC1, the code is available at:
https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.
