### ISSUE TITLE
Commands on user page is visible only in the language of buying

### ISSUE THREAD

**Issue by aladin-99** [hyyan/woo-poly-integration#129]
If i want to see user order in their page if i'm not in the language use for buying the order it doesn't appear but are visible in the language which was used for order. Since i read the features of the plugin, that's probably an enhancement feature since the user page doesn't appear in those features.
BTW Thank's for that really nice plugin
![image](https://cloud.githubusercontent.com/assets/26879262/24623241/c5f2edf6-1875-11e7-9c03-2a2a225bcf9c.png)
![image](https://cloud.githubusercontent.com/assets/26879262/24623308/fbd46238-1875-11e7-9f42-22619ff36b5f.png)

**Comment by aladin-99** [comment]
I forget to tell that i'm using Pinpoint booking system from dot on paper. Can't it be an issue from that plugins?

**Comment by Jon007** [comment]
Confirmed Bug, I get this as well.

**Comment by Jon007** [comment]
fixed by decarvalhoaa in woocommerce2.7 branch and included in release under preparation for wooCommerce 3.0

My Account, Orders page only shows orders in current language. You can test this but checking out and placing orders in different languages. Then when you visit the orders page, and use the language switcher, for each language you only see the orders for that language.

See also:

https://wordpress.org/support/topic/my-account-order-list-only-in-current-language/
woocommerce/woocommerce#12643

**Comment by Jon007** [comment]
Fixed in pull request 0.30RC1, the code is available at:
https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.

**Comment by aladin-99** [comment]
I test the 0.30 version. The bug seem to be corrected. The my account - order show both language order. Seem to be fixed

Thanks
