### ISSUE TITLE
SyntaxError: Unexpected token C in JSON at position 1

### ISSUE THREAD

**Issue by secretrivers** [hyyan/woo-poly-integration#131]
Dear Hyyan,

Since the update of WC 3.0 we receive the following error message in the frontend when placing an order: _SyntaxError: Unexpected token C in JSON at position 1_

In the backend the orther is coming in but not receiving an invoice number. The WC Support mentioned that your plugin isn't 3.0 ready yet. Do you know when you will be able to release an update and fix?

**Comment by Jon007** [comment]
Fixed in pull request 0.30RC1, the code is available at:
https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.
