### ISSUE TITLE
Translation of woocommerce_email_footer_text

### ISSUE THREAD

**Issue by repli2dev** [hyyan/woo-poly-integration#140]
There is a configuration of text in the email footer in Woocommerce -> Settings -> E-mails option "Footer text" (called `woocommerce_email_footer_text`), this text seems to be untranslatable which is unfortunate.

**Comment by Jon007** [comment]
I had a look to see if it could be possible to implement this.:

- Short answer: no.
- Longer answer: maybe - Second opinions welcome.
- Conclusion: use theme template as a workaround.  

## No - because wooCommerce doesn't provide the target language information

The individual order email filters have an $order parameter which allows woo-poly-integration to query the order language and translate the email text into that language.

However the 'woocommerce_email_footer_text' filter is called from many contexts and has no order parameter or other context information, that could tell woo-poly-integration what language the email should be sent in...
(The footer is also be used by out of stock and other alert emails sent to shop admin email or woocommerce_stock_email_recipient so doesn't necessarily have an order.)


## Maybe - it could be possible to detect the context or get an enhancement from wooCommerce

I tried implementing a solution assuming the language switch is already done by the time the footer is called so we should know the target language, but I'm not sure this can be done reliably.
Otherwise we may need an enhancement from wooCommerce on this filter to be able to implement successfully.


## Workaround - copy email template to theme and add your own translateable strings there

Until then wooCommerce does provide a button to copy email templates to your theme, you could then implement whatever text you like in your theme, translateable via either theme text domain translation files or indeed Polylang string translation.
