### ISSUE TITLE
Product picture is not being displayed in RTL

### ISSUE THREAD

**Issue by PragmaticTurtle** [hyyan/woo-poly-integration#152]
Hi there,

First, i'd like to thank everyone contributing to this project. I'm working on a website that use both english and arabic, I'm running:
WordPress 4.7.4
WooCommerce 3.0.5
Polylang 2.1.3
Hyyan WooCommerce Polylang Integration 0.29.1
SiteOrigin North Theme.

The problem is that the products picture is not being displayed on the arabic product page. So everything is displayed properly on the category and sub category pages, but it’s not displayed when you go to any individual product page. 

Someone tried to help me at WordPress forums, but he told me that Hyyan WooCommerce Polylang Integration 0.2.9.1 doesn't work with WooCommerce Version 3.0.5, but somehow it worked for me, he also suggested changing those options for Polylang:

– I have unchecked featured image synchronised translation.
– Deactivated Media activated that enables different pictures for different languages.

Still no luck after changing this. I would really appreciate any help or assistance.

Thanks!

**Comment by theleemon** [comment]
I don't know if your problem is related buy try to download and install an updated version of the plugin from the following repository:

https://github.com/Jon007/woo-poly-integration

It's updated to work with WooCommerce 3.0.

**Comment by Jon007** [comment]
thanks theleemon, it's true we can't offer advice and support on PragmaticTurtle's setup because we already know it can't work, however:

@PragmaticTurtle 
"– I have unchecked featured image synchronised translation.":

1. This option needs to be ON, it must be checked if you want the featured image to be synchronised.  Turn it on and check again.  
2. This is a Polylang option, not a woo-poly-integration option, so it doesn't belong in this forum and is independent of versions of woocommerce and  woo-poly-integration.
