### ISSUE TITLE
Fatal Error during Checkout

### ISSUE THREAD

**Issue by mjke87** [hyyan/woo-poly-integration#157]
I Updated to WooCommerce 3.0, now I get the following fatal error during checkout.

```
[10-May-2017 09:02:21 UTC] PHP Catchable fatal error:  Argument 1 passed to Hyyan\WPI\Product\Stock::change() must be of the type array, object given, called in /home/httpd/vhosts/<domain.com>/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Stock.php on line 56 and defined in /home/httpd/vhosts/<domain.com>/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Stock.php on line 90
```

The error occurred in the following scenario:
1. Checkout with multiple products in default language (note: some products have no German translations)
2. Payment method BACS
3. Press Checkout button
4. Error message appears on Frontend (Internal Server Error) and the checkout page is still visible
5. Order gets processed correctly in Backend, Email sent and stock updated correctly
6. One odd thing is that one of the products in the Email is shown with the German title
7. Cart is empty afterwards (after going back to shop)

Setup:
- Configured languages: English (default) and German
- WooCommerce Version 3.0
- Polylang Version 2.1.3
- Hyyan WooCommerce Polylang Integration Version 0.29.1 
- Chrome Browser Version 58

**Comment by Jon007** [comment]
Hyyan WooCommerce Polylang Integration Version 0.29.1 does NOT work with WooCommerce 3.0.
see the 0.30 RC1 Pull Request or release branch here:
https://github.com/Jon007/woo-poly-integration/releases

**Comment by mjke87** [comment]
I tested with version 0.30RC1. The problem does not occur anymore, thank you very much.

**Comment by Jon007** [comment]
Good - The tool is pretty complex as there are a lot of options in wooCommerce - and  Polyang - to deal with (as well as >50 options in the woo-poly) tool, so quite a lot of testing is needed.

As far as we are aware RC1 should solve the issues caused by breaking changes in WooCommerce3, however it doesn't synchronise Featured product / Product visibility at the moment, and RC2 will include a rewrite of Product taxonomy and attribute synchronisation to address this and a number of other enhancements in this area.
