### ISSUE TITLE
Catchable fatal error: Order List on Dashboard getProductTranslationByObject() is being given a Boolean instead of an WC_Product Object

### ISSUE THREAD

**Issue by Nathaniel401** [hyyan/woo-poly-integration#16]
First,

Let me say thanks for taking the time to make this plugin; it's greatly appreciated!

I am having a problem after upgrading my WooCommerce and WordPress cores. I am getting the following error when looking on my Orders list in the dashboard:

```php
Catchable fatal error: Argument 1 passed to Hyyan\WPI\Utilities::getProductTranslationByObject() must be an instance of WC_Product, boolean given, called in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Order.php on line 105 and defined in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Utilities.php on line 88
```

Cheers man!

Nathaniel

**Comment by ebelrose** [comment]
Just push corrections for this.
Let's see if the plugin author accepts it.

**Comment by razcakappa** [comment]
@ebelrose Did your pull request accept? I'm having the same error which @Nathaniel401 has.

**Comment by decarvalhoaa** [comment]
I have been patching and develop further this plugin. I have included ebelrose pull in my fork. Can I suggest you use my fork at https://github.com/decarvalhoaa/woo-poly-integration/releases/tag/v0.27

Note that I have not test it yet with WC 2.6. I don't usually upgrade immediately after a release to field, since in the first months there will be plenty of issues being raised and solved, and testing all this releases is time consuming.

**Comment by ebelrose** [comment]
No,  there was no commit on this project in 11 months so I presume it's dead

**Comment by hyyan** [comment]
[PR](https://github.com/hyyan/woo-poly-integration/pull/28) is  accepted  , thanks
