### ISSUE TITLE
Problem with price on cart and checkout

### ISSUE THREAD

**Issue by janyazul** [hyyan/woo-poly-integration#173]
Hello, on my page I have two languages, Spanish and English, I need the price to appear in Spanish in English and in English it appears in dollars, but the prices are different in each one, for example in Spanish the product costs $ 500 mxn and in English $ 30 usd. I have set the prices in the products for each language and I am using the "Polylang for WooCommerce Multi-currency support" plugin to make the currency change and everything works correctly if I use one language at a time.

My problem is when a product is already added to the cart and I change the language, the price does not change, if for example I added it on the Spanish page and change it to English, the price comes out as 500 usd instead of changing it to 30 usd. 

How can I get the price updated when I change the language or how can I empty the cart when the language change?

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.7.5
* WooCommerce:  3.0.7
* Polylang:  2.1.5
* Hyyan WooCommerce Polylang Integration: 1.0.0
* Browser:

**Comment by Jon007** [comment]
It's not generally the best idea for the currency to be linked to language.
for example: 
- a customer in Spain would prefer the price to be in Euro not mxn
- a customer in UK would prefer the price to be in GBP and not USD
- equally a Spanish speaking customer based in USA might prefer Spanish language but USDollar currency, and vice-versa
Equally there are many other English and Spanish speaking countries with different currencies.

So normally the currency should be related to user country and user choice rather than fixed to language.

Polylang for WooCommerce Multi-currency doesn't seem to be in the WordPress.org repository?
You will probably solve this most quickly by checking with the author or debugging it or checking alternative solution.

**Comment by SillyMe727** [comment]
I am using the 'Currency Switcher for WooCommerce' Plugin by Algoritmika Ltd and it works great.

**Comment by Jon007** [comment]
@SillyMe727  thanks for the tip on the Currency Switcher plugin..
.. do you know if it is compatible with SuperCache?

I prefer to use a caching tool that generates and uses cached html, as this enormously increases the server throughput..  but it's most efficient if any dynamic information like cart or currency switcher is filled in by javascript

**Comment by SillyMe727** [comment]
I briefly used Super Cache and did not seem to have any issues. I am back to W3 now and Autoptimize and it works well too.

**Comment by hyyan** [comment]
@SillyMe727 polylang currently does not provide any hook to detect language changes, so I am not sure this is possible but you can try something like :

```php
add_action( 'init', 'woocommerce_clear_cart' );
function woocommerce_clear_cart() {
  global $woocommerce;
  
  if(pll_current_language() == 'de') {
     $woocommerce->cart->empty_cart();    
  }
}
```
Closing as this issue is not related to woopoly plugin

**Comment by Jon007** [comment]
@SillyMe727  I noticed that Currency Switcher for WooCommerce adds Product level per-currency pricing:  if used this will not be copied be copied to Product translations.  
I added an example here to show how to synchronize it if needed:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

**Comment by SillyMe727** [comment]
Thank you. I'll have a look.
