### ISSUE TITLE
All languages share the same product tags?

### ISSUE THREAD

**Issue by auching** [hyyan/woo-poly-integration#178]
Why must all language versions share the same product tags? e.g. I have english product tags for english version, chinese product tags for chinese version.  But now I cannot separate them, which means I have to use all english & chinese product tags in both versions of a single product.  If I add more languages, I have to use all different language tags in every copy??

- PHP: 5.6.30
- WordPress: 4.7.5
- WooCommerce: 3.0.7
- Polylang: 2.1.5
- Hyyan WooCommerce Polylang Integration: 1.0.0
- Browser: Chrome Version 58.0.3029.110 (64-bit)

**Comment by Jon007** [comment]
I'm not quite sure what you mean...
check [Settings\WooPoly, Features](https://github.com/hyyan/woo-poly-integration/wiki/Settings---Features) setting for Translate Tags
- If this is Off, then Tags don't have a language, you just get the same Tags coming up in every language
- If this is On, then Tags have language and translations.
   - One change is that missing Tags may now be added as copy of source language, instead of simply disappearing in the second language..

**Comment by auching** [comment]
e.g. i need "t-shirt", "blue t-shirt" product tags in one of my products in english version.
For the same product in Chinese version, I only need "恤衫", "藍恤衫" product tags in the same product in chinese verison.

and then the plugin replaces the english version of that product with all my chinese tags

**Comment by Jon007** [comment]
no, it doesn't normally, please answer the questions:
- can you see the flags on the Products, Tags page, eg /wp-admin/edit-tags.php?taxonomy=product_tag&post_type=product ?
- have you checked: Settings\WooPoly, Features setting for Translate Tags /wp-admin/options-general.php?page=hyyan-wpi  ?
- check also in Polylang, Languages Settings /wp-admin/admin.php?page=mlang_settings  in the part Custom post types and Taxonomies, Custom taxonomies,  Product tags should be cheked

**Comment by auching** [comment]
Yes for all, and already checked.

Do you mean I have to translate the tag one by one in order to display different language tags in different language version?  That would be a bit crazy.. since for SEO purpose, I don't use exact same meaning tags for each language even for the same product..

**Comment by Jon007** [comment]
ah ok, so you don't want to the tags to be separate but not translated?
Maybe we should have an option for that.

But then you would have to add the tags separately every time...
For example if the tag is translated, you just add T-shirt once to the English version - I think you can even do in bulk edit - and then you automatically get 恤衫 in Chinese and related tag in every other language.

I guess an option could be added to not add the translation entries for tags, they are added for Categories and Terms because they are kind of structural and actually breaks the system in unexpected ways if you save a translation by mistake with missing Category or Term.

For tags it's also not damaging to have an extra tag and useful to have a reminder that you got tags not translated.
If you are cleaning up your tagging there are also tools like https://wordpress.org/plugins/term-management-tools/ which still seem to work for merging tags or even moving tags to categories etc

**Comment by Jon007** [comment]
I was playing around with this and thinking what the options could be if we allow more options, for example:

Tag translation options:

- [ ] No Translation/Shared Tags - Product shows same tags in all languages
- [ ] Enable translation - when saving a product, only translated tags will be copied to product translations
- [ ] Enforce translation - when saving a product, tags are always copied to product translations, missing tags are auto-completed by copy source and can be translated later
- [ ] No Translation/Independent Tags - All product translations are tagged independently, there is no Tag translation or synchronization

**Comment by auching** [comment]
thank you for doing this.  the first option might be redundant? as the third option already cover this scenario.

**Comment by Jon007** [comment]
No, the third option is completely different, in the third option which is the best option, you create your tag for "T-shirt" and then if you didn't translate it yet, yes you get "T-shirt" copied to your Chinese translation of product, but then you go back to the Products\Tags screen and translate Chinese "T-shirt" to "恤衫" or whatever and automatically the system is updated so:
- chinese product only shows 恤衫
- English product only shows T-shirt

However in option 1, both Chinese and English products would have to show both "T-shirt" and "恤衫"..   but wait... in option 1, what do you expect to happen if someone links on the tag link for "恤衫"?    Actually it depends a bit on your Polylang configuration, but either Polylang doesn't know what language the page is supposed to be or it has to assume you are in Shop base language:  if that's English, then when you click on 恤衫 then you would get only English products!


Actually I'll explain why the third option is correct and why the other options are bad and try to write it better in the documentation:

- Product Tags are NOT for SEO keywords: SEO keyword type stuff should be part of your product description, excerpts etc
- Product Tag is actually a way of grouping different products together in the system, like Product Categories, but in a flexible way.
    - Product Categories are a hierarchical way of organising the product catalogue
    - Tags are a way of grouping products from different categories: Tags are shown as a link on the Product page which links to a Tag page which has it's own slug and description and so on.

In this way, the tags are relevant for search engines because each one is a separate linked page which will be found and indexed.   If all your products have different tags and you have lots of different Tag pages with one product each, this would be bad SEO and actually might be counted by Google as duplicate content, since you basically have multiple pages with the same content, the Product page with 1 product and the tag page with one product.

Also if the Tags are not translated, this means that your site has pages which are not translated, you cannot switch language on those pages.

**Comment by Jon007** [comment]
I try simpler explanation:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Tags

**Comment by auching** [comment]
Yes you're right.  I was thinking about your previous comment too.  Maybe I should restructure my tags instead.  Thanks for your advice.

**Comment by Jon007** [comment]
No problem, I had the same thing when starting to use the system, I guess I thought "Tag" means something like markup for SEO, but when you realise it is really a type of page or category it is quite a different perspective.
