### ISSUE TITLE
Shipping Methods

### ISSUE THREAD

**Issue by galenashop** [hyyan/woo-poly-integration#186]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0.19
* WordPress: 4.7.5
* WooCommerce: 3.0.8
* Polylang: 2.1.5 
* Hyyan WooCommerce Polylang Integration: 1.0.1 
* Browser: Chrome

#### Steps to Reproduce
1. Hyyan WooCommerce Polylang Integration updated from 1.0.0 to 1.0.1 
1. 
1. 

#### What I Expected
Shipping Methods in Polylang

#### What Happened Instead
Shipping Methods in Polylang disappeared

**Comment by Jon007** [comment]
I think it's a change on the WooCommerce end - you must have also just updated WooCommerce to 3.0.8 since this was only released yesterday :)

shipping.php l.143 is trying to get setting as:
`                $setting = get_option($plugin_id . $method_id . '_settings');`
there the option string will be eg: woocommerce_flat_rate_settings.
However the settings is not found so this must have changed...

**Comment by Jon007** [comment]
@hyyan  this is error in the woo3 compatibility removal, the wrong part of the code is removed in getActiveShippingMethods() and so the code is now trying to use the wooCommmerce < 2.6 version.

**Comment by Jon007** [comment]
this is a one line change in getActiveShippingMethods() 
l.109 should read:
```
            $shipping_methods = $this->getZonesShippingMethods();
```
and the shipping methods will reappear

**Comment by galenashop** [comment]
Thank you very much, it's ok now.
