### ISSUE TITLE
Wordpress 4.8 udpate broke translation of posts

### ISSUE THREAD

**Issue by xbytes** [hyyan/woo-poly-integration#191]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 4.8
* Polylang: 2.1.5
* Browser: all browsers

#### Steps to Reproduce
1. My website is www.agorapublicaffairs.com and issue appears under section cases (casos in spanish and portuguese)
2. Posts listed in this section belong to the casos/cases category.
3 After updating to wordpress 4.8, the titles and content of posts is not translated when switching language. This did work before update.
4. When I access the post and change language, the contents do get translated.

#### What I Expected

I expected the listed posts to display title and content in the language that corresponds to the selected language.

#### What Happened Instead

Title and contents of the listed posts always show in spanish, no matter what the current language is.

**Comment by Jon007** [comment]
I commented on the 4.8 issues in the [pinned post in the wordpress support forum](https://wordpress.org/support/topic/do-not-install-wordpress-4-8-if-you-use-variations/) and on issue #187.

Please note that:
- if your issue is with Posts, then that needs to be reported to (Polylang)[https://wordpress.org/support/plugin/polylang] - this plugin does not manage the translation of posts, it only extends Polylang for WooCommerce (Products) - please make sure you have latest Polylang as they do now claim to support 4.8
- if your issue is with Products then see issue #187 and please try the 1.0.2 branch code
