### ISSUE TITLE
WooPoly is not managing Stock for variable products correctly 

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#198]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes 

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.25
* WordPress: 4,8
* WooCommerce:  30.8
* Polylang: 2.1.5
* Hyyan WooCommerce Polylang Integration:  master , beta2
* Browser:  all

#### Steps to Reproduce
*  create variable products (not translation and stock is not managed) 
*  try to order new product  (**does not work** : `Sorry, this product is unavailable. Please choose a different combination`)
* activate manage stock for the product  
*  try to order new product  (**does not work** : `Sorry, this product is unavailable. Please choose a different combination`)
* activate manage stock for variations 
*  try to order a new product  (**does not work** : `Sorry, this product is unavailable. Please choose a different combination`)

#### What I Expected

Stock is managed correctly in the frontend when the options is activated 

#### What Happened Instead
**does not work** : `Sorry, this product is unavailable. Please choose a different combination`

**Comment by Jon007** [comment]
Hi @hyyan 
This is working perfectly for me...  I just retested again on 1.0.2 branch in base language and translations...

This message is correct if there is no Stock for that particular variation.. 
> Sorry, this product is unavailable. Please choose a different combination

If stock is added then it can be ordered normally, it also decrements correctly when order is placed ..

**Comment by Jon007** [comment]
@hyyan 
master should not work for variations with WP4,8.
1.0.2 contains other fixes for variations and WP4,8:  getTermBySlug was not the only issue to be addressed.

Seperately, there was a bug in one version of 1.0.2 for creating new variations, this was due to a reworking of code in variable.php, not variation.php.  
This change was reversed on 16/June and 1.0.2 branch should now be working normally for variations.

**Comment by Jon007** [comment]
I just found some Variation add to basket problems on production (with 1.0.2).

However my problem was due to additional security software enabled on production environment, which was blocking some ajax requests.
The fix was to put the security software back to learning mode, then everything worked again.

The error symptoms were different depending on whether WooCommerce, Settings “Redirect to the cart page after successful addition” is enabled.

 - If enabled, there was the error adding to cart since woo-poly is not getting the variation info due to previous hidden failed call, raised by cart.php .300                 throw new \Exception(__('Please choose product options&hellip;', 'woocommerce'));

 - if not enabled there was  an on screen message:
ERROR: That action is currently not allowed.
and nothing in PHP error log.

I just mention in case related to any problem you are seeing.

**Comment by Jon007** [comment]
this should be closed in 1.0.2
