### ISSUE TITLE
When linking two existing product pages, variations are not synced.

### ISSUE THREAD

**Issue by michiphp** [hyyan/woo-poly-integration#203]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes
#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
yes
#### What product versions and settings are you using when this issue occurs?

*PHP: 4.0.10.14
*WordPress: 4.8
*WooCommerce: 3.08
*Polylang: 2.1.5
*Hyyan WooCommerce Polylang Integration: 1.0.2
*Browser: any

#### Steps to Reproduce
1. Create and publish two product pages, one variable in default language and one simple in second language. But dont link them to each other for now. 
2.  Now go into the language editor of the default language page and link it to the second language product page. Update.

#### What I Expected
All metas are synced between default and second language product page including variations.

#### What Happened Instead
All of the metas are synced but the variations are not created.

**Comment by Jon007** [comment]
Correct, this is not supported currently.
May be best linked to #168 re-engineering of variations support.

**Comment by michiphp** [comment]
is there a work around for this (apart from using the +)... many thanks!

**Comment by Jon007** [comment]
Hi, @michiphp we discussed that on #187

> Yes, just import the second language without the variations.
Then when you go link the translations the variations will be created automatically, that's expected.
It doesn't matter if you do the linking and saving from master language or second language.

Or just don't import the second language, just use the + and copy and paste the translated description from your source.

**Comment by michiphp** [comment]
Hi Jon007, thanks for your help! I've tried both:

Inporting as simple product: when I link from default language, it will sync everything with the product in second language, but the variations are not created! Then I go into the second language page, and without changing anything, I press update, and the variations are created. But then for some reason it transfers wrong info from the simple product in second language to the linked product in default language! (which is why I posted the issue #202). Then I have to go back to the product in default language and press update again. then it works....

and yes it makes a difference linking from second language or default language!!

**Comment by Jon007** [comment]
@michiphp ok I get it, thanks for confirmation, 
I have tried to update the notes on this page to reflect this:
https://github.com/hyyan/woo-poly-integration/wiki/Upload,-Bulk-Edit,-Quick-Edit

Maybe you can suggest any further correction that may be needed or any special note for the import tool you are using.

**Comment by michiphp** [comment]
thanks for the summary on how to use woo-poly with an import tool! Its pretty useful, and I don't have anything to add currently.

However, I was wondering whether there is a solution to this issue already? 

The reason someone would use an import tool is that he has so many products that he cant handle each individually. 

so a workaround to go into each product and press update can be pretty time consuming,

hope there is a solution soon. Many thanks to everyone who is contributing to this!

**Comment by Jon007** [comment]
Well, as another tip, if you have to do a lot of editing, like adding a new language, then turn off all non-critical plugins and hide unnecessary sections of the page while you are doing it as a lot of them add to the product page load.  
If you have Yoast readability and addins for republishing to social media and linking to other stores etc, maybe you can turn them off at least for products in order to be able to speedily open and re-save a set of products.

Actually I had a lot of other problems with the woocommerce importer, when exporting and reimporting the products, the catalogue was broken in ways that were not immediately obvious and took some days to resolve - this was due to not handling commas in category descriptions and product attributes and nothing to do with Polylang.   This particular issue is now fixed, but this importer is fairly new and I won't be trying it again for now. The others I've seen also have their problems so either way you need to test carefully for your use case - and balance the time and cost of that vs the more manual options. 

A lot of plugins work the other way round using woocommerce as the master and exporting to other platforms, this is generally fairly reliable and compatible with Polylang as you tend to be able to select the categories you want to export and control the language that way, though of course every target system has its issues.

**Comment by hyyan** [comment]
Closing for same reasons in #168
