### ISSUE TITLE
Orders always auto check for translation

### ISSUE THREAD

**Issue by imknight** [hyyan/woo-poly-integration#205]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.1
* WordPress: 4.8
* WooCommerce: 3.09
* Polylang:  2.1.5 
* Hyyan WooCommerce Polylang Integration: 1.01
* Browser: Chrome

#### Steps to Reproduce
1. unchecked Language -> Settings -> Custom Post Types -> Orders
2. refresh WooPoly Setting page
3. Check back the Language Settings, Order is checked again.

#### What I Expected
Order remain unchecked.

#### What Happened Instead
checking on the source code, it seem like keep added the Orders need translation setting back to option table, is that a must ?

**Comment by Jon007** [comment]
Question:  
- why would you want to turn off Language settings for Orders?
- If an Order doesn't have a language, how would it know which language version of the Product to show?

Note that you don't have to translate the Orders, it's just that the Orders are associated with the language the customer selected so that all the emails etc can be sent in that language.

 So yes, I guess at the moment Products and Orders would be forced translation on.


Noting your versions, please be aware that there are some issues with 4.8, especially with variations, which require the code from the 1.0.2 branch of this plugin.  Also I haven't tested this plugin with WooCommerce 3.0.9 and won't now 3.1 is out

**Comment by Jon007** [comment]
closing - please open if there is a specific requirement identified
