### ISSUE TITLE
NumberFormatter error

### ISSUE THREAD

**Issue by FabriceFRANK** [hyyan/woo-poly-integration#222]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

#### What Happened Instead

Whoops \ Exception \ ErrorException (E_ERROR)
Class 'NumberFormatter' not found

/var/www/xxx/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/LocaleNumbers.php105

  
 public function getLocaleDecimalSeparator($separator)
    {
        $retval = $separator;
        //don't touch values on admin screens, save as plain number using woo defaults
        if ((! is_admin()) || isset($_REQUEST['get_product_price_by_ajax'])) {
            $locale = pll_current_language('locale');
            $a = new \NumberFormatter($locale, \NumberFormatter::DECIMAL);
            if ($a) {
                $locale_result = $a->getSymbol(\NumberFormatter::DECIMAL_SEPARATOR_SYMBOL);
                if ($locale_result) {
                    $retval = $locale_result;
                }
            }
        }
        return $retval;
    }

**Comment by Jon007** [comment]
you will get such an error if the php_intl.dll extension is not enabled.

You need to enabled it in php.in file something like
extension=ext/php_intl.dll

NumberFormatter is part of intl extension bundled with PHP since PHP 5.3 (2009): http://php.net/manual/en/class.numberformatter.php
[If you are using a version older than that you should definitely upgrade. Please note that everything prior to PHP 5.6 is currently considered old and unsupported by the developers of PHP. There are no security releases for older versions.}

And if you are running a multi-language site it makes sense to have the internationalization extension enabled..

Also the formatting feature can be turned off from the Settings page, ie: /wp-admin/options-general.php?page=hyyan-wpi under Features, Use locale number formats.

This is also discussed on: https://wordpress.org/support/topic/update-to-1-0-2-breaks-site/

**Comment by FabriceFRANK** [comment]
OK.
I'll upgradre PHP. Thank you for jour answer.
Regatds
--
Envoyé depuis l'application myMail pour Android jeudi, 03 août 2017, 09:13AM +01:00 de Jonathan Moore  notifications@github.com :

**Comment by hyyan** [comment]
Version 1.0.3 . will avoid the error , please update

**Comment by FabriceFRANK** [comment]
Works perfect now, great job, thank you
