### ISSUE TITLE
WooCOmmerce Point of Sale issue

### ISSUE THREAD

**Issue by henrilindeberg** [hyyan/woo-poly-integration#226]
When translation of Coupons, categories, tags and attributes enabled, the Point of Sale plugin not loading these.

WooCommerce Point of Sale: https://codecanyon.net/item/woocommerce-point-of-sale-pos/7869665

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
It looks like WooCommerce Point of Sale (POS) is a paid commercial product which includes support.  
Whereas Hyyan WooCommerce Polylang Integration is free open-source code with no paid version so is community/self support only.

So if it's support you need I would refer to WooCommerce Point of Sale. 

Since the source code for WooCommerce Point of Sale (POS) is not freely accessible we may not be able to advise from this end.  However, if it uses the standard wooCommerce functions, the translation functionality should be available.

**Comment by henrilindeberg** [comment]
Point of Sale author resolved this. Thanks!
