### ISSUE TITLE
Problem with language switching on Shop page

### ISSUE THREAD

**Issue by Marijulama** [hyyan/woo-poly-integration#231]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6.22
* WordPress: 4.8.1
* WooCommerce: 3.1.2
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

#### What Happened Instead

Hello,
I have a problem regarding Polylang Language switcher with WooCommerce. If I am on a Product Page (with add to cart, description, etc..) The Language switcher works as expected. But if I am on the WooCommerce Shop site (Where all products are listed) the language switcher redirects me to a specific product every time instead of showing the shop site in the 2nd language.. So if users try to switch the language form Default(German) to 2nd(English) while being on the shope page, they will get redirected to a product page in the default language.

Is there a way to achieve this? So that there will be a shop page  with all products of 2nd language?

Any help is greatly appreciated.

Best Regards from Germany,

Timo

**Comment by OurCoterie** [comment]
Hi there!

I have a similar problem with the shop page. Everything works great until you try to access the Romanian version of the shop page. In which case the page only shows (in Romanian) "Showing the single result".

Thank you

**Comment by Jon007** [comment]
I suggest checking for these types of common problems:
- Have you translated the shop page?  
- Are the translated pages correctly linked?  check the languages panel and relink if necessary
- What is the content of the translated shop page?   Actually it can just be blank.
- Check the slugs and permalinks involved, to be sure there is not a clash and potential misinterpretation of the url
- any redirects in .htaccess which could be deliberately or accidentally affecting the url

**Comment by OurCoterie** [comment]
In my case (and I'm sorry, I don't want to hijack the thread which is why I opened my own where I explained in more detail):

- Have you translated the shop page? **Yes**.

- Are the translated pages correctly linked? check the languages panel and relink if necessary. **Yes**.

- What is the content of the translated shop page? Actually it can just be blank. **Same as the original English page, but different words. I don't want it to be blank, I want it to be in Romanian, not every visitor know English and it might be a deterrent for them.**

- Check the slugs and permalinks involved, to be sure there is not a clash and potential misinterpretation of the url. **To my knowledge, there isn't. One is "shop" the other is "shop-2".**

- any redirects in .htaccess which could be deliberately or accidentally affecting the url. **I don't know where to look for this one.**

**Comment by Jon007** [comment]
@OurCoterie  I have identified your problem and solution on #232 
Polylang setting URL modifications, The language is set from content  is not supportable.
I suspect that @Marijulama has one of the other problem types

**Comment by Marijulama** [comment]
Hello,
Thank you for time. I checked your first point 'Have you translated the shop page?' And i thought yes of course i did... But when i double checked i realised that it was not actually published.. *facepalm*

--> Problem solved.
Feeling bad for not noticing this.


Best Regards,
Marijulama
