### ISSUE TITLE
Saving variable product

### ISSUE THREAD

**Issue by Krislynde** [hyyan/woo-poly-integration#243]
Hey!

I like your plugin very much, it has been a lifesaver on my rocky way through language plugins. 
You seem to have so many fans here and they've all posted so many useful stuff - but I can not seem to still find a solution to mine. 

I use a free version of Polylang. 
Everything works fine when the product doesn't have any variations. 
But when there are variations added, the saving process takes me to the page where I can read "This page isn’t working". Refreshing it takes me to the wordpress Posts admin section. 
Also the plugin doesn't sync the prices (the option is checked in the settings).

Is there something I have missed in the configuration? Have you any suggestions I should do about this?

Greetings from Estonia,
Krislynde

Edit: I forgot to mention that when saving, some parts of the variable product get saved but for example the settings for Yoast do not get saved. That is not the case when the product doesn't have variations.

**Comment by Jon007** [comment]
Do try turning Yoast and other plugins off and check again.
An exact sequence of events may be needed to replicate the issue.
This is why there is a questionnaire for when you report an issue (which you did not complete).

Also this general type of error can sometimes occur due to rules in .htaccess or mod_security.

Basically turn everything off as much as possible, in fact even turn off this plugin and confirm you can save a variable product normally, then turn it back on and repeat.

**Comment by Krislynde** [comment]
Hi!
Thank you for such a quick reply. 

I know I didn't give the answers to all of these questions, I am sorry. I will try to answer those now as much as I can:

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Haven't had a chance to try this out. 

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes, same thing happens.

#### What product versions and settings are you using when this issue occurs?
* PHP: PHP 7.0
* WordPress: 4.8.2
* WooCommerce: not the latest one but the one before that - this is because of the notice of possible incompability with some plugins, including yours. 
* Polylang: free version, 2.2.3
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Chrome, Firefox


#### Steps to Reproduce
I couldn't tell anything about reproducing this behaviour. It has been like this from the beginning. I believe I installed your plugin sometime in the spring.

#### What I Expected #### What Happened Instead
Well, I already wrote about these two. So I won't be duplicating that here again.

But I did the tests you suggested and one of those is described above already  - turning the plugins off except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration. 
The other test - to turn off the plugin itself - then I can save the product with variables without any problems. 

Please let me know if you get more ideas about this and please let me know if there is something more I should defenetly do.

**Comment by Jon007** [comment]
>Well, I already wrote about these two. So I won't be duplicating that here again.
Hi, actually no you didn't, not in enough detail to be able to help?

at what exact point in the process does this occur?  For example, is it when clicking the '+' to create the translation?   Or when clicking the save button?  do translations exist at this point or do you mean just saving a new variable product with no translations created yet?

Can you give php error log extract at this point?   (it may not have anything)

Can your run with Chrome Developer tools, to see if there is any javascript error?

Some versions of Yoast had big javascript which was causing some problem with editing products which is why I asked about turning that off.

Otherwise you need to check what is the exact url being requested, for example in Chrome Developer tools.    Is the browser getting into a redirect loop or is it a status error, what error is being returned?   For example if redirect loop then check:
 - is there any rule in .htaccess which could match up with the url being requested
 - are you triggering any rule in mod_security or similar on the server?

If you have any additional security tools turned on, whitelist your ip or put the tools back to learning mode to avoid any possible error with the tool. 

But these are general comments, it's not possible to understand your situation without a lot more details.

**Comment by Krislynde** [comment]
Hi once again. Thank you. 

All the products have translations. This occurs when I click the save button. 

Yes, Yoast was turned off when I did the previous tests you suggested. 

I was just planning some additional information as I was playing with the plugin and variable product  today, trying to understand what could be wrong here. So I can give few more answers right now.

I noticed that just saving the product as a variable product doesn't hurt anything, saving works. 
Now when I add the attribute - then also nothing goes wrong, saving works.
But when I create the variations from the attribute, then it stops saving normally. 

When deleting and adding new variables to the products I also noticed that syncing doesn't seem to work. It doesn't matter what I choose or not from the settings page - that doesn't seem to change anything for me. 

When you say javascript error, do you mean something from this:
JQMIGRATE: Migrate is installed, version 1.4.1
1508113179
Empty queue 15731->15731
XHR finished loading: POST 
XHR finished loading: POST 
XHR finished loading: POST 
XHR finished loading: POST 
POST https://www.nahakamber.ee/wp-admin/post.php 500 ()
Navigated to https://www.nahakamber.ee/wp-admin/post.php

Other questions are unanswered right now - I need some time to firstly understand what are you asking and then finding the answer. So I will get back here as soon as I have figured everything out.

**Comment by Jon007** [comment]
How to the products have translations if it doesn't work?
You have creating the products as standard products and then switching to variable afterwards?

If there is a 500 error, check wordpress debugging in enabled eg in config file:
```
// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );
// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );
// Disable display of errors and warnings
define( 'WP_DEBUG_DISPLAY', true );
```
now try again:

Create a new product as a variable product, in the site first language and create and save the variations and save the product.

Does that work?  - if so, save and create translation

If not, what is the error?  get detail from the log.
Try again with this plugin turned off to ensure you can create variations normally.
(If you can't then there is a different problem not this plugin)

**Comment by Krislynde** [comment]
Yes, that was it, the debuging mode. 
Fom there I got the information that there is something wrong in my functions.php file for my child- theme. I have added some functions for woocommerce into my functions.php file. I just cleared all those out to get the answer if that will solve the problem and seems that it did. There is no problem to save the product with variables  any more. Now I just have to go on and try them one by one to make sure which one actually is the cause of this. 

Thank you.
