### ISSUE TITLE
Tax rate label not translated

### ISSUE THREAD

**Issue by atai1960** [hyyan/woo-poly-integration#250]
Hello!

I don't know if this is an issue about Woocommerce or about this plugin.
On my cart page the only word not traslated in Japanese is the tax rate label.
I see in Italian "Imposta di consumo".
Is there a way to translate it in Japanese?

Also che checkout page contain words not translated.
For example:
the labels:
product-name and product-total
cart-subtotal
order-total
and place-order button

Many thanks

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1.

**Comment by Jon007** [comment]
within the system there are actually 2 types of label:

1) WooCommerce, Settings, Tax, Tax Options, Price display suffix.
This IS translateable and can be found in Languages, Strings translations, WooCommerce Taxes

2) WooCommerce, Settings, Tax, Tax Options, Standard rates
These are not translateable and do not need to be translated because they should use the correct tax name for the country (country specific not language specific).


For example, if you are in UK the tax is "VAT", if you are in Spain the tax is "IVA", in France the equivalent tax is "TVA", in Australia the tax is called "GST":  which tax will be applied depends on the country more than the language.


You may not need to translate the Price display suffix either.
For example, if you are VAT registered in UK, then you may be charging VAT to shoppers in other EU countries (UK VAT at UK tax rates, not the equivalent IVA or TVA - unless you also have a warehouse and tax obligation in those countries).   In this case it would be incorrect to translate the tax as IVA or TVA since it is VAT that is being charged, not IVA/TVA.
