### ISSUE TITLE
get_posts product_variation

### ISSUE THREAD

**Issue by Stibo** [hyyan/woo-poly-integration#261]
Hey guys.

I have a get_posts function that selects ALL product variations ('post_type' => 'product_variation'). Now this function returns the variations for EVERY language. How can is modify the call to select only variations for the current language? 'lang' => 'de' does not work. Or is there another way to select ALL product variations?

**Comment by Jon007** [comment]
why don't you post the code for your function?

probably you should get the variable products (the products are filtered by language) and then get the variations of those products.

**Comment by Stibo** [comment]
I dont think the code is necessary, because I described it well. But here you go:

`get_posts(array(
			'nopaging' => true,
			'post_type' => 'product_variation',
			'post_status' => 'publish',
			'lang' => 'de',
			'suppress_filters' => true
))`

Is there a reason why you dont link the variations together as translations? So we can use default polylang functionality to select this variations or use functions like pll_get_post?

**Comment by Jon007** [comment]
I meant the wider context, not just that one line, as it's hard to advise the best way to do it without understanding what you are trying to do.

Use wc_get_products() to get woocommerce products and you just get the variable products by language and access their variations from there.
eg
wc_get_products( array ('type' => 'variable') )
would return the variable products 

I have floated the idea of re-engineering the variations in #168, but actually this would cause more overhead on the taxonomy tables which are some of the biggest queries in this setup already and probably not worth it since there is essentially no point in getting the variations by themselves.

There is essentially no point in getting the variations by themselves because Product variations are not complete products without getting other information attached the parent which is not available at the variation level, so to be compliant and compatible with wooCommerce you should be following its api in this way.

Unless you have some completely different use case which you haven't explained and I haven't been able to imagine.

**Comment by Stibo** [comment]
Thanks for the detailed answer! That makes sense because of the overhead. BUT you should consider a compromise, because if you disable the plugin, you lose all the translations for the variations. I did this once to try another plugin and had a huge mess after that. If you use normal translations then your plugin is more compatible with other plugins like Polylang for Woocommerce etc.

**Comment by Jon007** [comment]
Polylang for WooCommerce is a paid plugin and if they want to implement a migration script they are welcome.
Hyyan plugin was written about 2 years earlier than Polylang for WooCommerce so didn't take this into account.
Hyyan plugin is only supported by the community / unpaid volunteers in their spare time, anyone is welcome to submit such a migration script if they want to, including you.
Then maybe we can close this down and just tell people to use the paid version :)
Is it any good?  The trouble with closed source and lack of a public issues list is you really can't tell the coverage and extent of issues unless you buy it.  Which I don't want to do in case I unconsciously and unintentionally use ideas from that in fixes to this one.

I don't think you should lose the links by deactivating and reactivating though.
It would also be possible to reestablish the Hyyan links but doing a script based on the code sample in #168
