### ISSUE TITLE
Language independent products

### ISSUE THREAD

**Issue by szepeviktor** [hyyan/woo-poly-integration#264]
Good afternoon!

Is there a way with your plugin to

- enter product details once (in one language)
- sell the same product in every language ?

**Comment by Jon007** [comment]
1. If you want to do that you don't need a plugin, you can just uninstall Polylang...  For example you can just use a language switcher like JSM's User Locale to allow the front end language change for plugin texts and use the same content.
2. this plugin does allow copy source language so you can create copy of the source language product in the other language with the original text.   So that's two clicks for each product, hit the plus on the language to create it and then press save...

**Comment by szepeviktor** [comment]
Thank you @Jon007 !

We have some Pages that need Polylang.

**Comment by Jon007** [comment]
Sure... you can also consider using WordPress multisite and using different plugins on each site.

I have an example, I put forums and directory on a child site with no Polylang as we are not going to translate the user-submitted content.  On the child site we allow the front-end user switching so that the bbPress and directory labels and instructions are shown in the user's preferred language.
We use code from JSM's User Locale for the child site front end language switching, also picking up the Polylang cookie if there is one so we know which language is supposed to be displayed.
This can be integrated so that user should not be aware of transition to a different site.

https://www.inkston.com/    - main site with Polylang and wooCommerce
https://www.inkston.com/community/   - child site with bbPress and Business Directory
https://www.inkston.com/deu/   - separate site for German, because we don't know German and 3 languages x 600 pages/products was enough already for the main site

If I was doing it again, I'd certainly consider putting wooCommerce on a separate site too if there are going to be more than a few hundred products.

**Comment by szepeviktor** [comment]
Thank you for your detailed answer.

Probably we go by Polylang Pro for WC and product synchronization.

**Comment by Jon007** [comment]
I don't think they do that, according to their text they do "Duplicate the content when creating a translation" which is the same as this plugin.

**Comment by Jon007** [comment]
oh, is it:   'Two posts can even be synchronized to appear the same in different languages.'

Actually this would be quite a small change to allow this:  at the moment the text is copied on save only for new posts, it would be a minor change to hook the save post and copy to other language posts.  

However it doesn't seem like a good idea: separate posts and the language lookup taxonomy queries on every single call is a noticeable overhead which is unnecessary if you are not going to translate. 
If you are not going to translate the products at all then you can save all that overhead and increase performance by not running Polylang on the woocommerce part of your site.

**Comment by szepeviktor** [comment]
> by not running Polylang on the woocommerce part of your site.

Sound like a lean solution!
Thank you.

It leaves the question open how to switch language by URL as we need multiple languages for the theme and plugins although product details will be available on a single language.

**Comment by Jon007** [comment]
In my example, for the community site, the language flags are menu items with links like: 
?update-user-locale=fr_FR
?update-user-locale=es_ES
?update-user-locale=en_GB
these parameters are supported by JSM User Locale.

I then forked JSM User Locale to add support for the Polylang cookie and language switching when the user is not logged in, the fork is here:
https://github.com/Jon007/jsm-user-locale

Use at your own risk, the changes are fairly minor and there are probably other ways of doing it, but this changes the locale and it is picked up by plugins and themes.
