### ISSUE TITLE
Can't edit product data

### ISSUE THREAD

**Issue by vitorgomateus** [hyyan/woo-poly-integration#265]
Thanks for contributing &mdash; you rock!

Please note:
- These comments won't show up when you submit the issue.
- This is free software supported by volunteers in their spare time.  Please help us by making your issue report as clear and simple as possible.
If reporting a problem please make sure you confirm the following points so we can reproduce and fix your problem as quickly as possible:
-->

#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Didn't try.

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Didn't try. But when I deactive this plugin (Hyyan's) the problem disappears.

#### What product versions and settings are you using when this issue occurs?
* PHP: not sure, will check asap
* WordPress: 4.9
* WooCommerce: 3.2.4
* Polylang: 2.2.5 
* Hyyan WooCommerce Polylang Integration: 1.0.3
* Browser: Opera

###Problem
Can't edit product data when this plugin is activated.

**Comment by Jon007** [comment]
Note that Hyyan WooCommerce Polylang Integration 1.0.3 does not claim compatibility with wooCommerce 3.2.4 and you should have had some warnings about that before upgrading, please use 3.1.1.  There are some changes in the master branch to fix some issues.

However there should not be issue editing products.
Do note that when synchronisation is enabled, then most product attributes should be edited in shop base language only, because when you save they will be copied from source language to base language.  The fields locker prevents you editing these fields in the other language (since such changes would be lost when you save).

If you have a different specific problem, please reopen with more details as to exactly what the problem is.

**Comment by Jon007** [comment]
no problem, do have a look through the documentation and wiki https://github.com/hyyan/woo-poly-integration/wiki
as there are quite a few options depending on how you need to manage your shop.
