### ISSUE TITLE
Missing Arguments 3 and 4: Not working with Woocommerce Product Bundle

### ISSUE THREAD

**Issue by ruymanbr** [hyyan/woo-poly-integration#267]
Product versions and settings:

 **PHP:** 7.0.25
 **WordPress:** 4.9
 **WooCommerce:** 3.2.4
 **WooCommerce Product Bundles: 5.6.1
 **Polylang:** 2.2.6 [not PRO]
 **Hyyan WooCommerce Polylang Integration:** 1.0.3
 **Browser:** All of them.

**Steps:**
1. Create a bundle product with variable child products.
2. Go to frontend or Product list, and see the error.

I expected a normal view in shop loop, but it crashes on every "product bundle".

It seems it can't pass the 3rd and 4th arguments in: 

function --> _Hyyan\WPI\Tax::filterPriceSuffix()_

called in --> _.../.../wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Tax.php on line 97_

**But this happened instead:**

Shop Loop in frontend and Product list in backend crashes in every product bundle. It displays everything else correctly, except for these.

It could be that I have taxes deactivated, but I tried creating a "catching" tweak inside the function for this particular issue, but didn't work as expected.

**Comment by Jon007** [comment]
Question and 1 observation:

- which version of which Product Bundle component?  

- WooCommerce 3.2.4 is not supported yet - and will never be supported due to the rapid release of 3.2.5: there were various breaking changes in 3.2, there are some fixes in the master branch, please try these - these cannot be fully tested yet due to the rapid releases of woocommerce fixes 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5..   One hopes that 3.2.5 may be a more stable release, but it's only been out for 2 days ..

**Comment by ruymanbr** [comment]
Hi Jon007. 

Unfortunately those things you commented (those fix) as far as I see in the commit dates have nothing to do with this. Only 2 days ago and they are about img fixing, not about Bundle product's Arguments passed and conflicting 'cause they are not plain variable products, but bundles of them.

**Comment by Jon007** [comment]
Please state which bundle plugin you are using and which version.

WooCommerce, out of the box, does not have a 'bundle' product type, so this would not be discussed on the WooCommerce github project.

My point was not that there are relevant fixes in WooCommerce 3.2.5.
My point is the opposite: THIS plugin does not work with WooCommerce 3.2.x yet, and there will not be a version tested and release for use with 3.2.4.

Since you are using versions of woocommerce and woocommerce polylang integration which are NOT compatible and not fully tested (and will not be), you will definitely have problems.

Since your problem is also with a mystery component you have not identified, it's very unlikely that anyone can help you.

If you are willing to reveal which component it is, and to test it with WooCommerce 3.1.2, then you could reopen this issue.

**Comment by ruymanbr** [comment]
I updated it to add "WooCommerce Product Bundles" version.

**Comment by Jon007** [comment]
Really????

Please bear in mind that there are several different plugins called "WooCommerce Product Bundles" such as EffectIO WooCommerce Product Bundles, YITH WooCommerce Product Bundles, etc , really it is best to specify which one and the version number, just to be sure in case anyone has experience and can help you.

In any case you need to try with WooCommerce 3.1.2 to rule out 3.2.x compatibility issues.

**Comment by ruymanbr** [comment]
Hi Jon007. Please re-open the thread.

I linked the plugin URL. It's the original WOOTHEMES Woocommerce Product Bundles.

**Comment by Jon007** [comment]
Please report to Woothemes.

Please note:
- WOOTHEMES Woocommerce Product Bundles is a commercial product, with a support team who are actually paid to answer your questions.
- Hyyan WooCommerce Polylang Integration is a free and open source product with community/self support from volunteers in their spare time.
- Woocommerce Product Bundles is not open source so the community cannot examine the source code and comment. The open source community can only fix the component to work with other open source components.  
- WooCommerce 3.2.x has breaking changes which cause it not to work correctly with Hyyan WooCommerce Polylang 1.0.3.  If Hyyan WooCommerce Polylang 1.0.3 + WooCommerce 3.2.x is already not supported, then we can't accept component compatibility issues on this combination.   
You are welcome to test with the master branch or with WooCommerce 3.1.2, but there doesn't seem to be much point in having an open issue about a combination of incompatible versions.
