### ISSUE TITLE
Checkout Thank you page issue 

### ISSUE THREAD

**Issue by sanjay003** [hyyan/woo-poly-integration#269]
I am using hyyan woocommerce polylang . its working good but. I have one issue  when I am trying to checkout ,After checkout its redirect on cart page with empty cart message. while after checkout its have redirect on thank you   page. Tried Multiple time  but no success.   Please any help ?.

**Comment by Jon007** [comment]
@sanjay003  you seem to have deliberately ignored the template explaining what information needs to be completed in order to raise an issue.

You have not explained what versions of software you are using or what payment gateway etc etc etc 
Have you read all the documentation as I advised you on wordpress.org only a few minutes ago?

Try get everything working with one of the built-in gateways such as cheque payment, to ensure it is not a gateway problem
