### ISSUE TITLE
Coupon with multiple products error

### ISSUE THREAD

**Issue by TeemuSuoranta** [hyyan/woo-poly-integration#27]
There's a bug when you create a coupon for multiple products and then try to buy for example one of these products and use this coupon. The error states that coupon can't be used.

I snooped around the source code and commented everything in Coupon.php and it's working for now. For what I undestood the logic there was that you could make one coupon and make it possible to use it for translated products as well. Personally there was no need for this as you can create separate coupons (with translated coupon codes) but I wanted to share my work-around.

My guess is that bug has something to do with the function that gets translated versions or the WooCommerce expects the IDs to be in different format.

**Comment by decarvalhoaa** [comment]
I have solved this issue in my 1.0.0 dev branch.

> Personally there was no need for this as you can create separate coupons (with translated coupon codes) but I wanted to share my work-around.

Consider you want to offer your Facebook fans a discount. This approach would not be very clean because you would need 2 coupons with FACEBOOK1 and FACEBOOK2. Some customers may complain.

You could however add both products translation ids in the coupon, therefore having a single coupon name for all of the languages. But this would be painful, for shop owners/managers that have already a mono-lingual store up and running and now just want to add a new language. Painful because this work around would mean editing all existing coupons. 
You idea also would required extra effort.

That is why I found it important to solve the issue instead of removing the feature all together.

**Comment by TeemuSuoranta** [comment]
Great, I'll make this issue closed. I didn't mean to remove this feature. I commented it as a quick fix because there was weird bugs when trying to apply coupon with multiple products. At the time I didn't have the time to look for the cause. Thank you for the fix!
