### ISSUE TITLE
Woocommerce-subscriptions: limit to one active subscription

### ISSUE THREAD

**Issue by philippehenri** [hyyan/woo-poly-integration#270]
Hello
Is this product compatible with woo commerce subscriptions? 
Lets say I have two linked products:

 - prod-En (english version)
 - prod-Fr (french version)

I note that If I order a “subscription” for PROD-EN, I cannot order a second one (the flag “limit to one active subscription is set), great, this is the expected behaviour.

but... I can still order the linked product PROD-FR ? which is not the expected behaviour ...

thanks
philippe

**Comment by Jon007** [comment]
Which product is this, is the the woothemes woocommerce subscriptions which is a paid product which has a support team which is paid to answer questions?

Because this is a free product supported only occasionally by volunteers / community / self support.
Since woocommerce subscriptions is not open source and I do not own it, I can't comment, even if I had time.

The quickest solutions are likely to involve raising to woothemes and trying to debug it yourself. 

This plugin only supports the plugins WooCommerce and Polylang.   If you are adding other plugins that don't now about Polylang then either you or the author would need to make the adaptations to that plugin for those.

**Comment by philippehenri** [comment]
ok well noted, sorry for having disturbed  - yes woocommerce subscriptions -  I dont have enough expertise with WP plugins to be able to debug this myself.
