### ISSUE TITLE
Product language version not listed properly in when displaying an order

### ISSUE THREAD

**Issue by philippehenri** [hyyan/woo-poly-integration#271]
Hello
Lets say I have two linked products:

 - prod-En (english version
 - prod-Fr (french version)

1/ I switch to FR version of the site, and i order “prod-fr”

everything is fine

2/ then, i switch to EN version of the site, and ask to display the order, the “prod-fr” product is listed instead of the proper EN version: “prod-en” ?

it happen also the reverse way of course... (order prod-EN version, switch to FR site, display the order: PROD-EN is displayed)
thanks 
philippe

**Comment by philippehenri** [comment]
ps: in fact the product link seems in the correct language, but not the product name displayed (my-account/view-order/xx)

**Comment by Jon007** [comment]
Please note that there is a form that needs to be filled in when you raise an issue which has important information on it such as the version numbers of the key components which it is necessary to know before giving any advice, so I will close this issue until this information is provided.

Having said that, this type of situation is most likely a data problem.
For example you have mixed up the titles in your product translation?
Another thing that can happen is that if some of the translations are not published, then the product will be processed in the available language.

For example, let's imagine this series of events:

1. product is published in english, but the French version is not published (maybe it is left in draft by mistake)
1. browse the site in English and add the product to the cart
1. switch language to French
1. since you have the item in the cart in English, and there is no published French translation, then the cart will show you the english version and checkout with the English version
1. after checkout there is a french order with an english product
1. Now publish the French version of the product
1. The French order is still linked to the English product but the system may now get the correct link for the french version when displaying the order
