### ISSUE TITLE
Document correct/acceptable settings for permalinks 

### ISSUE THREAD

**Issue by ElectricFeet** [hyyan/woo-poly-integration#273]
Hi there,
Thanks for the plugin. Much appreciated.

Browsing the documentation, I cannot find any recommendation for permalink settings. I vaguely remember that this could be an issue with Polylang and Woocommerce (but have a lousy memory). I'm hesitant to move forward with configuration until I know if there are any pitfalls in this area.

Would it be possible to put setting recommendations into the documentation? (Or &mdash; if it's not an issue &mdash; an indication that it's not an issue and you can select what you like?)

I saw [this page on the polylang site](https://polylang.pro/doc/translating-woocommerce-urls-and-strings/), but it's not clear to me if these are recommendations or per personal choice.

I would be happy to write up the changes for you, but I need to know what they should be.

Thanks for any help you can give!

**Comment by Jon007** [comment]
Please feel free to improve the wiki if you think there is something missing:
https://github.com/hyyan/woo-poly-integration/wiki

The only special note would be that the Polylang setting language is set from content is not compatible.

Otherwise, it is recommended that you set up Polylang and WooCommerce and ensure these working first before adding and configuring this plugin.  As long as Polylang is working, this plugin should work.

**Comment by ElectricFeet** [comment]
Thanks @Jon007. I updated the wiki.
