### ISSUE TITLE
Tax class not syncing between translations

### ISSUE THREAD

**Issue by Johuspect** [hyyan/woo-poly-integration#291]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
Yes 

#### Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?
Yes, in various installations

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0
* WordPress (DE): 4.9.1
* WooCommerce: 3.2.6
* Polylang: [state if using Polylang PRO] 2.2.7
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Storefront: 2.2.5
* Browser: Firefox

#### Steps to Reproduce
1. Completely new installation of Wordpress with Plugins Woocommerce, Polylang and Hyyan Woo Polylang. (additional Plugins WP Mail SMTP and Antispam Bee)
2. Standard Woocommerce Products installation 
3. creation of two languages in Polylang
4. activation of tax classes in Woocommerce and creaion of 3 diffeen tax classes
5. assining "reduced tax rate" (DE: "Ermäßigter Steuersatz") to a product and press publishing
6. opening 2nd language of this product 

#### What I Expected
Opening the 2nd language of this product the tax class should be as well "reduced tax rate"

#### What Happened Instead
Opening the 2nd language of this product the tax class was "Standard"

#### Addition
Doing step 5. and 6. again, but with tax class "tax free" all works perfectly!
Could the error be due to the German letters "äß"?

**Comment by Jon007** [comment]
I just tested with "Ermäßigter Steuersatz" and it still works for me...
try running in debug and see if there is anything in the error log?

**Comment by hyyan** [comment]
@Johuspect  still an issue ?

**Comment by Johuspect** [comment]
Sorry for answering so late.
Yes, it is still an issue and no error is signalled in debug mode. 
If you like I can give you access to my test set-up ad you can test yourself what's oing wrong.

**Comment by Jon007** [comment]
any further update?
I can't think of anything but check also Settings, WooPoly, Metas that both tax attributes are set to be synchronised.
/wp-admin/options-general.php?page=hyyan-wpi
though I assume they are if some tax classes are working...

**Comment by Johuspect** [comment]
I have tried it again and with Wordpress en_US platfrom all is fine.
But taking Wordpress de_DE I can repeat the error that 'reduced rate' (German: "Ermäßigter Steuersatz") is still substiuted for another language by "Standard". 
So it seems with the Wordpress in Geman (maybe other languages) something goes wrong.

**Comment by taxifisch** [comment]
Hi, 
are there any updates on this issue? Am having the same issue with an install using WordPress de_DE_formal.
If you found a workaround, how did you do it?
Thanks für getting back. :)

**Comment by taxifisch** [comment]
To add.. As a bit of a dirty workaround it does work if you just omit the special letters we use in written German (ä, ß etc) and write "ermaessigt" instead of "ermäßigt". Need to add the tax rate afterwards, but that's not really a lot of work in this case.

**Comment by Jon007** [comment]
@Johuspect @taxifisch I just noticed Polylang 2.4.1 release notes include "Fix title slugs for posts written in German" which could be of interest to test re this issue

**Comment by Johuspect** [comment]
Hi Jon007, thanks for the information, but I just tested it with:
WordPress (DE): 4.9.8
WooCommerce: 3.5.2
Polylang: [state if using Polylang PRO] 2.4.1
Hyyan WooCommerce Polylang Integration: 1.2.0
... and it still doesn't work.

**Comment by Johuspect** [comment]
Hi taxifisch, - sorry for the late answer - in the properties of WooPoly I switched of the Tax class meta and do it by hand. More to do, But it looks better ;)

**Comment by Jon007** [comment]
I think the tax class synchronisation is correct.
However the tax class name is not shown on the front end at all.

What may be shown on the front end in the checkout tax area before the total is the name of the tax rate within the tax rate class.
On the other pages you just see the tax suffix string, which is translatable in Polylang String Translations.

I am not entirely sure it is correct to translate the tax name:  if the shop is in the UK, VAT is always VAT even if you are buying in German or Spanish because that is the legal name of the tax.  
If you are buying from a shop in Spain, the tax is always IVA. 

This name of the tax rate is not translated by woocommerce as it is a custom string, nor does this plugin add these strings to the tax translation table.
So we could open that as a separate issue if there is demand for it.

For this particular issue I will close it now but happy to reopen if  it is clear that it is still an issue and where this tax class name is seen and needs to be corrected - I could not see it.
