### ISSUE TITLE
Strange filter

### ISSUE THREAD

**Issue by chOse** [hyyan/woo-poly-integration#296]
So I was fighting to debug an issue with some recipients not receiving the new order email than I found this the plugin in file [src/Hyyan/WPI/Emails.php : 47](https://github.com/hyyan/woo-poly-integration/blob/master/src/Hyyan/WPI/Emails.php#L47)

`add_filter('woocommerce_email_recipient_new_order', array($this, 'translateEmailRecipientNewOrder'), 10, 2);`

I can't see what is the purpose of this filter since recipients shouldn't have to be translated.
Plus, the way the translateEmailRecipientNewOrder function is declared doesn't match the woocommerce_email_recipient_new_order filter.

Commenting this line solved my issue.

Thanks for the great plugin. 
I hope I could help improving it.

Regards

**Comment by Jon007** [comment]
The purpose of this is to allow different language orders to go to different customer service representatives.
The new order email is sent to the shop email address, and the value configured for this uses the Polylang string translation table to send to a language specific address if this has been configured.

**Comment by Jon007** [comment]
I still question what you mean by "some recipients not receiving the new order email"
the "new order" email is supposed to go to the shop - which is only one email (or its translation):  the customers receive the "order processing" or other email according to their status.

Have you changed the "new order" email to be sent to the customer instead of the shop?
Changing the meaning of the new order email could cause various problems and unexpected effects due to the workflow.
For example the new order email is only sent when payment is completed, not on pending payment (after payment failure for example).

in any case there is no need to hook all the parameters, filters can add parameters without breaking existing code, so unless there is some action to be taken with the additional parameters there is no need to hook them.

**Comment by chOse** [comment]
I'm using a multi vendor plugin (Dokan)
The same new order email is sent to the shop admin and the vendor of the product.
This feature is not compatible with your plugin, because of the sus-mentionned filter.

**Comment by Jon007** [comment]
well I'd like to understand why, is there anything in the logs??

The filter doesn't do anything other than look up the string in the string translation table, and returns the original string if there is no translation registered..

If "some recipients not receiving the new order email" but others are receiving it sounds more like an email problem than a plugin compatibility problem.

**Comment by chOse** [comment]
Yes, I'd like too!

Actually it's not an email problem because the email is sent with multiple recipients. So each recipient may see the list of recipients, and this is how I noticed that the vendor email is not added (when the above filter is not commented)

Here is third party module's implementation of the filter for adding vendor's email : https://github.com/weDevsOfficial/dokan/blob/639051f7c1981408301395084fbfd640b425f91a/includes/functions.php#L1575

**Comment by Jon007** [comment]
Well this is a simple filter priority conflict: both filters are added with priority 10 so only one of them takes effect - so if it's this one then the additional Dokan recipients won't be added.   
In this case the woopoly filter should be lower priority number as it should translate only the shop email (which is the only one registered in the string translation table) and the wedevs filter should get a higher priority number so it fires after other processing

**Comment by chOse** [comment]
Thank you. Will try this.
