### ISSUE TITLE
Redirection on home page when I change the language on the shop page

### ISSUE THREAD

**Issue by CaroleU** [hyyan/woo-poly-integration#304]
#### What product versions and settings are you using when this issue occurs?
* PHP: 7.0
* WordPress:  4.9.4
* WooCommerce: 3.3.1
* Polylang: [state if using Polylang PRO] 2.3.1
* Hyyan WooCommerce Polylang Integration: 1.0.4
* Browser: Google chrome  64.0.3282.167 (also tested on firefox)

#### Steps to Reproduce
1. Installed Polylang, duplicate all my pages successfully
2. Installed woocommerce and woopoly. Pages Checkout, Cart, My account and Shop has been created automatically.
3. I duplicate each of them with the polylang "+" button
4. All the page are perfectly working except for the shop page.
5. When I'm on the shop page and I want to change the language, I click on one of the language button
and it directs me on the home page of the language I choose (even if I select the same language I'm already seeing on the screen.).

#### What I Expected
It should translate the shop page into the selected language.

#### What Happened Instead
It redirects me on the home page of the language I selected.

## WordPress Environment

My theme 
Name: Divi
Version: 3.0.102

<details>
Home URL: https://carole-urban.com
Site URL: https://carole-urban.com
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
</details>

If somebody could help me please, it would be so great ! Thank you very much !

EDIT : my main language is french and the second one is english. I noticed that, even if my permalink to my english shop is  https://carole-urban.com/en/shop-en/, if I go to  https://carole-urban.com/en/shop/ it works the same, it's like there are two pages who lead to the same content. And if I try to edit the page by clicking in the link directly in the page (the wordpress bar on the top of the screen), I am guided to the same edition page, the one with the permalink  https://carole-urban.com/en/shop-en/. And I can't change it to  https://carole-urban.com/en/shop/, it's automalically changed to  https://carole-urban.com/en/shop-2/.
Of course, I already tried to delete this page and create it again but I get the same thing every time.

EDIT 2 : I upgraded to woocommerce 3.3.2 today (in case this could solve my problem but it doesn't).

**Comment by Jon007** [comment]
Typically this happens if the other language Shop page is not published, please check if all the translated pages are in status 'Published', if they are created but draft or pending you would get this behaviour  (standard Polylang behaviour, not part of this plugin).

**Comment by CaroleU** [comment]
Hello, thank you for your answer, yes I did publish it. Its status is well noted on "published" on the list of the pages. I tried several times to delete it (even from the trash) and recreate it but nothing solves this...

**Comment by Jon007** [comment]
try going to Settings, Permalinks, check woocommerce permalinks are set and press Save

**Comment by CaroleU** [comment]
everything is set, still doesn't work

**Comment by Jon007** [comment]
re-reading your post, I would say you must have 2 shop pages, only one of which is translated... but that doesn't seem to be it either.

French is the site main language yes?

Your French shop page seems to be:
https://carole-urban.com/shop/
from which the language switcher also points back to the English home page instead of the English shop page.

I can reproduce this situation when no products are translated, but that also seems to be not the case here.

I can see some individual product pages are ok:
https://carole-urban.com/shop/creme-fouettee/

I can't reproduce this and may be running out of ideas but I suggest:
- change the slug of the shop page in the different languages
- set Settings, Permalinks, Product permalinks, Custom base and press save (this is the most likely issue)

It doesn't really matter what these are - the product permalink could be just /p/  the shop page slug could be /magasin/ in French and /sale/ or whatever in english - I'm just ruling out conflicts at this stage...

Note: I have not tested WooCommerce 3.3.x, and this plugin does not declare support for 3.3.x - since WooCommerce make a lot of breaking changes in the updates I am still on 3.1.2.  This plugin should be ok with 3.2.6 but I would not be at all surprised if 3.3.x has some issue.

**Comment by CaroleU** [comment]
Thanks again for your answers. 
The english shop page points on the french one and vice versa (regarding the translation in WP).

Yes french is the main language.

Yes, you're right, it is the french shop page. And yes again, the two language switchers are pointing on the home page of the language they represent.

Yes I guess this is normal that the product which has no translation redirects us on the home page, I don't mind, I'm going to translate them all. The product pages seem OK when they have their translation so that's not an issue.

I changed the slug of the two shop pages and the permalinks but it didn't change anything.

I'm making a backup of my website right now and I installed WP rollback to downgrade my woocommerce to 3.2.6 as soon as this is finished. I'll keep you informed.

**Comment by CaroleU** [comment]
Ok, I'm on 3.2.6 and it's still exactly the same...

**Comment by CaroleU** [comment]
OK I have a lead.

I deleted the two shop pages. I recreated them and it's working. BUT woocommerce doesn't know anymore which is my shop page. And if I set my shop page in the woocommerce options, it doesn't work anymore.

**Comment by CaroleU** [comment]
Ok, I did it but it's still the same. I even changed the slug again to avoid any reference I would have missed but it doesn't change anything...

**Comment by Jon007** [comment]
when you say it is still the same, what do you mean... 
there's something wrong about your setup, I can't work out what the French shop page is now even in the French site..

**Comment by Jon007** [comment]
switch the theme to Storefront just to check there is not a theme conflict of some kind - you can always switch it back later..   .. it's unlikely but you have a very unusual situation..

**Comment by CaroleU** [comment]
When I say that it's the same, I mean the language buttons in the shop pages are pointing on the home page of their languages instead of the shop pages. The shop pages are now https://carole-urban.com/boutique and https://carole-urban.com/en/shopping/

**Comment by CaroleU** [comment]
I switched to storefront but I couldn't find where to switch language... I need to find out where the secondary bar shows up in storefront to tell you if it's a theme issue or not.

**Comment by CaroleU** [comment]
Ok, I found out. Aaaaand it's a theme issue...

**Comment by Jon007** [comment]
Actually this is the first question asked when raising a new issue:
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
This is important as some themes include a lot of functionality not just style and can introduce conflicting code.

**Comment by CaroleU** [comment]
I'm sorry I didn't try it out, I was afraid I was going to break everything on my site. And so, all I can do is to not use hyyan for polylang ?

**Comment by Jon007** [comment]
>all I can do is to not use hyyan for polylang ?
Huh???

You can:
1. use a different theme, for example Storefront or any of many many many thousands of themes which do not have this issue
1. you could report the issue to the authors of Divi - since Divi is a paid product with support, it is quite reasonable to report it to Divi.  - this plugin is only supported by unpaid volunteers in their spare time, who do not have access to Divi so can't reasonably be expected to debug a compatibility issue introduced by Divi
1. you could debug the issue and find out what the conflict is between Divi and WooCommerce/Polylang or this plugin, in the end it will probably be a simple change to one of these three components..

**Comment by CaroleU** [comment]
Ok, many thanks for your help.
