### ISSUE TITLE
Undismissable "welcome" banner in ALL pages

### ISSUE THREAD

**Issue by Magneticdud** [hyyan/woo-poly-integration#309]
Using latest wordpress and woocommerce and polylang

After the plugin update there's a "welcome" banner in all admin pages, which cannot be closed

very very annoying to the point that i disabled the plugin

**Comment by hyyan** [comment]
The welcome banner will be shown only once after the activation is successful and it can be closed 
@see the screenshot 
![capture](https://user-images.githubusercontent.com/4313420/37021980-c6a112ea-2121-11e8-8c28-1a3bfc1b8f18.PNG)

if you can not see the close button please fill the issue requirements so I can help

**Comment by Magneticdud** [comment]
i know how to close it, the problem is that it shows all the time

using firefox with anti tracking enabled, maybe the cookie is blocked (no I am not going to disable the anti tracking feature, I prefer to disable the plugin)

**Comment by hyyan** [comment]
@Magneticdud  OK! , as you wish

**Comment by Magneticdud** [comment]
i am not the only user in the world that uses firefox, you can't ignore the problem

don't be sad if you get bad reviews from angry users "the welcome banner shows all the time"

**Comment by hyyan** [comment]
@Magneticdud You are not describing a problem, plus you ignored all the issue requirements, you did not paste your plugins list or your woocommerce status. The issue is not clear and it can not be reproduced in Firefox or Chrome. "The Welcome Banner" does not use cookies at all. it uses WordPress database. 
And please understand, this is free software supported by volunteers in their spare time.  help us by making your issue report as clear and simple as possible so we can help.
