### ISSUE TITLE
Variations

### ISSUE THREAD

**Issue by rg122h** [hyyan/woo-poly-integration#331]
Hi there I started to work on woo-poly and it worked great in the start but I noticed there is a big problem with variable product. I set on the excisting product the default language and once I add the translated version it messes everthing up. It create random variations and the default language variations are not avaible anymore. Do you can help me on this one ? Thanks a lot

**Comment by Jon007** [comment]
Hi, there is a template to fill in when you open these issues, as in order to get any help we need to know exactly which versions etc you are using and exactly what you are doing to create the problem.

Please bear in mind that this is a free plugin supported by volunteers in their spare time - we don't have time to guess what your situation is.

I use variable products with 3 languages and it works fine.  In production I use woocommerce 3.1.2.  Released version 1.0.4 of this plugin should also work fine with WooCommerce 3.2.5.

WooCommerce 3.3.x has further breaking changes to the language on ajax calls for which there is a fix proposed here:
https://github.com/hyyan/woo-poly-integration/pull/329
