### ISSUE TITLE
Incorrect language for emails

### ISSUE THREAD

**Issue by theblackhole** [hyyan/woo-poly-integration#34]
Hello again,

It's seems like order emails are sended only in default language, even if "Use order language whenever woocommerce sends order emails" is checked.
The only translated email is the "cancelled order" email, sended to admin.

**Comment by decarvalhoaa** [comment]
try my fork at https://github.com/decarvalhoaa/woo-poly-integration/archive/master.zip

I fixed the email issues (at least the ones I have found in my config). If you change the woocommerce admin settings (emails headers and subjects) the strings will be added to the Polylang strings translations table so that you can translate your custom texts for the other language. Otherwise it will use the default woocommerce texts.

**Comment by theblackhole** [comment]
You rocks dude ! :metal: 

Everything seems to work properly after switching to your fork :smile:

**Comment by decarvalhoaa** [comment]
@hyyan You already have a PR that fixes Emails.

**Comment by hyyan** [comment]
The PR of @decarvalhoaa  has been merged now
