### ISSUE TITLE
Cart product filter may cause compatibility issues with other plugins which modify the cart contents

### ISSUE THREAD

**Issue by AdrienPierrin** [hyyan/woo-poly-integration#346]
Hello,

I work on a bilingual WooCommerce website and I got a conflict problem caused by the "Hyyan WooCommerce Polylang Integration" plugin. 

It seems that your plugin override the cart item's product object using the woocommerce_cart_item_product hook and this erases some properties of "WooCommerce Dynamic Pricing & Discounts" plugin.

My question is why not drop the current product completely and return a new one ? This can cause incompatibilities with other plugins too, not just "WooCommerce Dynamic Pricing & Discounts".

Can you help me with that ?
Thank you for your time.

**Comment by Jon007** [comment]
What the cart module does is display the right language version of the product _and also allow the wrong language version of the product to be shown if no translation is available_   

If it didn't do this then the products in the cart would not display when you change language or you would only see the products in the language you added them.


This is just a free plugin which only supports WooCommerce and Polylang, if you need to integrate other plugins with Polylang based solution, you would need to do your own integration or raise it with the authors of this plugin.

If you or whoever is doing it find particular hooks or options which need to be implemented in this plugin to allow your solution to work, then you are very welcome to suggest - ideally via pull request - and I am sure would be accepted.

**Comment by Jon007** [comment]
fixed in above commit

**Comment by Jon007** [comment]
@AdrienPierrin regrettably this was reversed as it was found to be incompatible with common currency switchers (#427) - if the already converted price is copied to the other language, it gets currency converted again giving the wrong value.

Since the plugin cannot decide what to do here, I added a filter instead.

Here is an example implementation for Product Open Pricing (Name Your Price) for WooCommerce
https://wordpress.org/plugins/product-open-pricing-name-your-price-for-woocommerce/

```
/*
 * filters woo-poly switch of display item in cart when switching languages
 */
function checkNameYourPriceItem( $newItem, $originalItem, $cartItem ) {
	if ( isset( $cartItem[ 'alg_open_price' ] ) ) {
		$newItem->price = $cartItem[ 'alg_open_price' ];
	}
	return $newItem;
}

add_filter( 'woo-poly.Cart.switchedItem', 'checkNameYourPriceItem', 10, 3 );

```

This sample does not include making Open Price compatible with currency switcher... !
