### ISSUE TITLE
Avoiding multiple language signature in domain

### ISSUE THREAD

**Issue by nassry** [hyyan/woo-poly-integration#357]
I'm having difficulties getting the perfect URL.

Does anyone knows how I can get from here:
https://tapaoo.com/backup-2/en/product-category/kudapan-en/

to something like this:

https://tapaoo.com/backup-2/en/product-category/kudapan/

Regards,

**Comment by Jon007** [comment]
thats purely down to the slug of your category, which you can edit however you like,
just go to /wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product
and edit the category..

Please note that categories and attributes should normally be translated before translating the products.  If there are missing category translations, this plugin will attempt to fill them in for you (otherwise this causes serious problems):  since the slugs should be unique, the plugin adds a language code to the automatically translated categories and attribute slugs which looks like what you see here.
