### ISSUE TITLE
Attributes' default values are lost

### ISSUE THREAD

**Issue by hubyc** [hyyan/woo-poly-integration#370]
#### What product versions and settings are you using when this issue occurs?
* PHP: 5.6
* WordPress: 4.9.8
* WooCommerce: 3.4.4
* Polylang: 2.3.11
* Hyyan WooCommerce Polylang Integration: 1.2.0
* Browser: Firefox 62.0.3

#### Steps to Reproduce
1. Create a prpoduct with variations and set default values (!)
2. Translate the product (plugin is set to sync everything) - works fine except:
3. For the translated product there are no default values
4. AND (!) the opriginal's product variations default values are also missing.

#### What I Expected

Not to wipe default values even for the original product

#### What Happened Instead

Default values are deleted.

**Comment by hubyc** [comment]
Just to share that the mentioned "fixed empty attribute for variations" doesn't fix the described problem.
It is very easy to replicate.
With simple words - when the [+] button is clicked to translate a product the next moment the default values for attributes lists defined for the product are deleted (for the original product and the copy) even before the new language version of the product is actually published.

**Comment by Jon007** [comment]
Hi, it works fine for update this is just a temporary problem when first creating the translation.
If you go back to the original product and reset the default value it will be carried over to the translation ok.

What is happening here is as follows:
 - when creating the new translation, the _default_attributes meta is created and saved correctly, but not updated correctly in the product object/screen.   On saving, the now blank product attributes are synchronised overwriting the original value.

I thought this might be fixable in syncDefaultAttributes() by adding 
`$product->set_default_attributes( $attributes_translation[ $_GET[ 'new_lang' ] ] );`
after or instead of:
`update_post_meta( $product->get_id(), '_default_attributes', $attributes_translation[ $_GET[ 'new_lang' ] ] );`
but that doesn't seem to do it.  I suspect that since the product is still a simple product at this point,  the default attributes must be reset/reloaded once it is created as a variable product.

Since my use case doesn't include this feature, and a simple workaround exists, I'm unlikely to find time to fix it further, any other suggestions welcome.

**Comment by Jon007** [comment]
actually this is a classic Polylang situation:
getDefaultAttributesTranslation() line
`                $term = get_term_by('slug', $value, $key);`
fails when creating a new translation because:
- Wordpress get_term_by fails to respect its own $filter = 'raw'
- Polylang filters the term query for the new post language: this means no results are found since we are trying to retrieve the term in original language to be able to translate it.. 

solution is to replace:
`$term = get_term_by('slug', $value, $key);`
with:
```
	$args = array(
		'get'                    => 'all',
		'number'                 => 1,
		'taxonomy'               => $key,
		'update_term_meta_cache' => false,
		'orderby'                => 'none',
		'suppress_filter'        => true,
		'slug'                   => $value,
		'lang'                   => pll_get_post_language($product_id)
	);
	$terms = get_terms( $args );
	$term = array_shift( $terms );
```
this works and does cause the correct default attribute to be saved both for new translation and existing translations, as can be seen when examining the database before saving the new translation on the screen.

HOWEVER this isn't enough to fix it, the same problem is still observed, the default attribute doesn't get back to the screen..

**Comment by Jon007** [comment]
ok I have a fix for this, a little complex but it was getting reset by Polylang: PLL_Sync_Metas->copy which attempts to reset the translated _default_attributes back to the original language version and the skipDefaultAttributesMeta() doesn't handle this correctly as the get_term_by() code doesn't take into account that this call fails when called by Polylang because it is itself filtered.
