### ISSUE TITLE
Order has the products in the original language

### ISSUE THREAD

**Issue by sumaiyamannan** [hyyan/woo-poly-integration#373]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
You need to actually fill in the details of the issue and the versions you are running otherwise no-one would really be able to help.

For example there was an order language issue appeared recently which appeared to be fixed by upgrading Polylang from polylang 2.3.10 to 2.3.11.
Also, if the products are not translated it would be correct that they appear in the base language.
