### ISSUE TITLE
Cannot change variant price for different languages

### ISSUE THREAD

**Issue by AdamJachocki** [hyyan/woo-poly-integration#417]
Hi, I have found information that it is possible to set different prices for different languages. I tried to do this, but without any success.

My Hyyan settings are default ones, but I have unchecked all items in groups:
- Stock Metas
- Taxes metas
- Price metas
- Variable metas

and Total Sales in General Metas.
Unfortunately I still cannot change price for variation in other language. It's just disabled. Please help me somehow.

I am a programmer, but with no programming knowledge about WooCommerce and Wordpress.

Hyyan version: 1.3.0
Woocommerce: 3.6.2
Wordpress: 5.1.1
PHP: 7.1.26
Polylang: 2.5.3
All in one Wp Security: 4.3.8.3
Cookie notice: 1.2.46
Duplicate Page: 3.5
Duplicator: 1.3.10
Loco Translate: 2.2.2
Really Simple SSL: 3.1.5
TinyMCE Advanced: 5.1.0
Visualizer: Tables and Charts Manager for WordPress (Lite): 3.1.3
WooCommerce Blocks: 2.0.1
WP Performance Score Booster: 1.9.2.2
WP Super Cache: 1.6.4

**Comment by Jon007** [comment]
the variation fields are locked by the Fields Locker: you can edit them by turning off the Fields locker under Settings, WooPoly, Features, Fields Locker.

The fields locker is there to avoid shop administrators changing fields which will be overwritten due to synchronisation, however at the moment there is a limitation in the fields locker for variations.

variable.php function extendFieldsLockerSelectors() merely excludes the variable_description from the fields locker and otherwise locks all the fields, without taking into consideration that synchronisation might be turned off for some fields.

What is the use case, why should a different language be a different price?
The native woocommerce products management screens do not make it easy to review variations and the fact that the same products may have variations may in different prices in different languages would not be easy to review and maintain when adjusting prices in  future. It may also be confusing to customers who switch language on the site and get a different price..   
Overall it can be done but I would be rather hesitant to recommend it.

**Comment by Jon007** [comment]
there's a filter for that in the code actually:
`        $variable_exclude = apply_filters(HooksInterface::FIELDS_LOCKER_VARIABLE_EXCLUDE_SELECTORS_FILTER, array( '[name^="variable_description"]' ));`

**Comment by Jon007** [comment]
try this update to variable.php which changes the field locking to respect and allow editing of unchecked meta.
