### ISSUE TITLE
Duplicated variations?

### ISSUE THREAD

**Issue by AdamJachocki** [hyyan/woo-poly-integration#418]
Hi, after duplicating my product to translate it and assigning a language, I thing that something weird has happened.

My original product consists of 2 variations (Ids are 95 and 96)
My translated product has 4 variations. Like it has doubled them. Ids are like: 295, 296, 301, 302.
But it seems like only 295 and 296 are valid.

What I have done:
- duplicate product (I couldn't add language in normal way, because it didn't work)
- edit duplicated product and assign languages and original product to it.

Hyyan version: 1.3.0
Woocommerce: 3.6.2
Wordpress: 5.1.1
PHP: 7.1.26
Polylang: 2.5.3
All in one Wp Security: 4.3.8.3
Cookie notice: 1.2.46
Duplicate Page: 3.5
Duplicator: 1.3.10
Loco Translate: 2.2.2
Really Simple SSL: 3.1.5
TinyMCE Advanced: 5.1.0
Visualizer: Tables and Charts Manager for WordPress (Lite): 3.1.3
WooCommerce Blocks: 2.0.1
WP Performance Score Booster: 1.9.2.2
WP Super Cache: 1.6.4

**Comment by Jon007** [comment]
This is expected behaviour, you can't do this by duplicating product, changing the language and relinking it, this plugin links the variations separately and as you have seen it recreates the variations if the linked variations can't be found.   This is the same reason you can't change the base language when using this plugin for variations.

It might have worked better if you saved it as a new product without any variations.
But really we need to see why the "normal" way did not work for you and raise a separate issue report about that.
And was it working previously with woocommerce 3.5.x?  (as this plugin is effectively untested with woocommerce 3.6.x it would be good to rule in or out any impact from 3.6 upgrade)
