### ISSUE TITLE
"Non offical" email templates not visible.

### ISSUE THREAD

**Issue by marqmedia** [hyyan/woo-poly-integration#421]
I have installed the plugin WooCommerce PDF Invoices & Packing Slips (Pro) and they have 2 e-mail templates on the email settings page (WooCommerce > Settings > Emails). Once I enable and activate the Hyyan WooCommerce Polylang Integration plugin, these 2 e-mail templates dissapear.
The creator of that plugin says that you do not support "non-offical" email templates. Do you have a small function which makes it possible for me to see these 2 extra templates, when your plugin is activated. Thanks!

**Comment by Jon007** [comment]
are you sure about that?
I have written plugins which add email templates to WooCommerce > Settings > Emails and this plugin does not make them disappear.
I also use WooCommerce PDF Invoices & Packing Slips, though only the free version which doesn't have extra templates, still I never noticed any incompatibility.

I have to close this issue though since:
1) this plugin does not support 3rd party plugins other than woocommerce and polylang.  (this plugin is free, your PRO plugin is paid and has a paid support team)
2) the issue needs to be raised according to the template and including the woocommerce status report 

Nevertheless I am wracking my brains to think what issue you could be having...  and I'll reiterate:
- this plugin neither adds nor removes any email templates from woocommerce
- adding emails is done via the woocommerce_email_classes filter which is not hooked by this plugin at all.

>The creator of that plugin says that you do not support "non-offical" email templates
What they may mean is that this plugin does not automatically provide translation facilities for the subject, header for custom emails.
That's a pretty minor issue though...  and there are hooks in this plugin to extend the email which I believe may have been added for woocommerce germanized.
There is also an example here which may give you a clue:
https://github.com/Jon007/inkston-integration/blob/master/_fn/plug-woo-poly-emails.php

**Comment by marqmedia** [comment]
Hi Jonathan,

 

Yes pretty sure. Once I disable your plugin they appear, but I need to make use of both great plugins.

The creator of PDF Invoices was pretty clear that you could create an extra function to allow these email templates.

I hope you can provide this code!

 

Thanks a lot in advance.

 


Met vriendelijke groet, 

Danny Marquering 
MarqMedia 




 <tel:0851306986> 085 130 6986




 <mailto:info@marqmedia.nl> info@marqmedia.nl




 <http://www.marqmedia.nl/> www.marqmedia.nl







	

 

 

Van: Jonathan Moore [mailto:notifications@github.com] 
Verzonden: zondag 19 mei 2019 23:41
Aan: hyyan/woo-poly-integration <woo-poly-integration@noreply.github.com>
CC: marqmedia <info@marqmedia.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [hyyan/woo-poly-integration] "Non offical" email templates not visible. (#421)

 

are you sure about that?
I have written plugins which add email templates to WooCommerce > Settings > Emails and this plugin does not make them disappear.
I also use WooCommerce PDF Invoices & Packing Slips, though only the free version which doesn't have extra templates, still I never noticed any incompatibility.

I have to close this issue though since:

1.	this plugin does not support 3rd party plugins other than woocommerce and polylang. (this plugin is free, your PRO plugin is paid and has a paid support team)
2.	the issue needs to be raised according to the template and including the woocommerce status report

Nevertheless I am wracking my brains to think what issue you could be having... and I'll reiterate:

*	this plugin neither adds nor removes any email templates from woocommerce
*	adding emails is done via the woocommerce_email_classes filter which is not hooked by this plugin at all.

The creator of that plugin says that you do not support "non-offical" email templates
What they may mean is that this plugin does not automatically provide translation facilities for the subject, header for custom emails.
That's a pretty minor issue though... and there are hooks in this plugin to extend the email which I believe may have been added for woocommerce germanized.
There is also an example here which may give you a clue:
https://github.com/Jon007/inkston-integration/blob/master/_fn/plug-woo-poly-emails.php

**Comment by Jon007** [comment]
@marqmedia  
about your comment "I hope you can provide this code!", sorry, no.

It is important that you understand that I do not have a copy of WooCommerce PDF Invoices & Packing Slips (Pro) which is not free and does not have freely available source code, so I cannot analyse what the compatibility issue could be.

I have given you quite a long answer including plenty of links and examples which should be sufficient for any experienced programmer to implement a solution.  
WooCommerce PDF Invoices & Packing Slips (Pro) is also a paid product which presumably has paid support people who could look at it, or someone from your company could do it or you could hire a freelance programmer.
I am just a volunteer helper here giving advice in my unpaid and extremely limited spare time.
