### ISSUE TITLE
Compatibility problem of Hyyan WooCommerce Polylang Integration with Redsys

### ISSUE THREAD

**Issue by alimaylivem** [hyyan/woo-poly-integration#443]
by using Hyyan WooCommerce Polylang integration on my wordpress site with woocommerce The REDSYS payment method stops working. Is there a solution for this problem?

Thank you

#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
To open an issue please provide the details requested and also details of what the problem is and what diagnostic steps have you taken
check php error log for any related errors
inspect the page with Chrome and check the console for any javascript errors

This plugin only provides compatibility layer between woocommerce and polylang plugins, as a free plugin it cannot possibly support every possible other plugin, though of course many payment provider plugins are used and working.
