### ISSUE TITLE
 products visibility synchronization

### ISSUE THREAD

**Issue by gourgoul** [hyyan/woo-poly-integration#460]
When i set original language product visibility to hidden the translated product is hidden too.
Then when i make visible again the translated product stays hidden.
I have to edit the translated product and make it visible again
(v 143)

**Comment by Jon007** [comment]
Hi, it is normally intentional that visibility is synchronised, however if you want to turn the synchronisation off, please see Settings, WooPoly, Metas - see documentation at https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas

I have tested this is still working even with with WP5.4.2 woo4.2.2 polylang 2.7.3 php7.4.2
but I don't particularly recommend it.

There are also other ways of hiding a product like marking it out of stock  etc.
