### ISSUE TITLE
How to get different downloaded products from different languages?

### ISSUE THREAD

**Issue by t7team** [hyyan/woo-poly-integration#473]
When buying a downloaded product, the client receives a file from the product of the main language.
I need to do to get the downloadable file from the product of the selected language because the files are different.
(Example: translated book, each language has its own translation of the book)

########
* PHP: 7.2.24
* WordPress: 5.3
* WooCommerce: 3.8.0
* Polylang: 2.6.7
* Hyyan WooCommerce Polylang Integration: 1.4.3
* Browser: Chrome

**Comment by Jon007** [comment]
Use a variable product with a variation for each language?
I know I prefer to choose the language of my book, which may not be the same as the user interface language I am using at the time :)

One thing you could try is turning off the meta synchronisation for the download file:
https://github.com/hyyan/woo-poly-integration/wiki/Settings-Metas
This may allow you to specify different file for different language.

otherwise might need a code customisation

**Comment by Jon007** [comment]
closing as no further feedback to provided suggestions in over 6 months
