### ISSUE TITLE
Hello. Just managing a little website for my karting club and I use Woocommerce for registration to event. I have a bilingual website (English/French) so I use Hyyan WooCommerce Polylang Integration to translate my shop and was working great until I updated WooCommerce to 4.1 (when from 3.XXX to 4.1). Now my problem is the French version of the shop doesn't work properly. Do you know if there is any update for the Hyyan extension planned? Thanks.

### ISSUE THREAD

**Issue by pttrck** [hyyan/woo-poly-integration#505]
#### What product versions and settings are you using when this issue occurs?
* PHP: 
* WordPress: 
* WooCommerce: 
* Polylang: [state if using Polylang PRO]
* Hyyan WooCommerce Polylang Integration: 
* Browser: 

#### Steps to Reproduce
1. 
1. 
1. 

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Jon007** [comment]
There are quite a few checkins since the last release so yes there will be an update.

However please note:

- there are no breaking issues reported with the upgrade from 3.x to 4.x at this time
- 4.x is not fully supported in terms of the fact that language handling for WooCommerce blocks and other new admin features have not been tested or implemented
- if you have a specific issue you need to report the full details of versions used and specific errors detected
