### ISSUE TITLE
 Inventory status does not synchronize when using the Stock Locations plugin for several warehouse locations

### ISSUE THREAD

**Issue by MarekBylica** [hyyan/woo-poly-integration#513]
**Can you reproduce this issue on default Wordpress theme (eg Storefront)?**

Yes.

**Can you reproduce this issue when all other plugins are disabled except WooCommerce, Polylang and Hyyan WooCommerce Polylang Integration?**

Yes.

**What product versions and settings are you using when this issue occurs?**
PHP: 7.2
WordPress: 5.4.2
WooCommerce: 4.4.1
Polylang: [state if using Polylang PRO] Free
Hyyan WooCommerce Polylang Integration: 1.4.3
Browser: Chrome

**Steps to Reproduce**

Hi! I'm using Your plugin with PolyLang and Stock Locations plugin (https://github.com/alexmigf/stock-locations-for-woocommerce) for multiple warehouse locations. When I create my product in two languages and place an order 
it doesn't change my stock properly. Every product in specific language behaves like a separate product with separate stock.
The stock quantity changes only for the language version of the product in which the language was set before placing an order.
Is there a way to handle this?

**Comment by Jon007** [comment]
Warehouse locations is a feature badly missing from WooCommerce.
This plugin only knows about WooCommerce, it can't know how to handle other extensions, if the other extension needs to support polylang, then it needs to implement it's own support or you need to implement your own plugin to bridge the gap..

I haven't checked the other plugin but I presume it replaces WooCommerce stock management with it's own stock management using different meta fields to handle the multiple locations.

If it is by meta then you can control by controlling which meta are synchronised by following the tips at:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields

ie, where they have:
`get_post_meta( $product_id, '_stock_at_' . $location->term_id, true )`
this type of meta beginning with underscore is not copied by default as per the documentation, so you can use the is_protected_meta hook to ensure that any meta beginning with '_stock_at_' is copied instead of being skipped
