### ISSUE TITLE
Translate woocommerce tax name

### ISSUE THREAD

**Issue by Mioleris** [hyyan/woo-poly-integration#59]
Is it possible to translate woocommerce tax name based on selected language ? PVM to VAT ?

**Comment by Jon007** [comment]
Hi, I've reviewed this and related tax requests:

- Shop display: there will be an implementation for translation of Price display suffix delivered on issue #104
- Cart and checkout display: uses WooCommerce language files translation
- Tax field in tax tables: translation not necessary, since the tax is per country, the country name for that tax is valid for that country and doesn't need translation.   For example the tax in UK is VAT and in Spain is IVA, I don't think it matters if you are shopping in a different language, the legal name for the tax applicable in that country is still the name which should be used.  For example, if you are in UK the legal name for the tax is VAT and that is the name which should be shown on the invoices if produced.  It doesn't matter if you are a French or Spanish person shopping in your own language, you'll still be paying UK VAT if you are in UK.
