### ISSUE TITLE
Variations sku are sync regardless of the Meta List setting

### ISSUE THREAD

**Issue by decarvalhoaa** [hyyan/woo-poly-integration#73]
Need help figuring out the right behavior here.

I guess that the SKU meta sync setting was intended for Product, Variable Products and Group Products but not to Variations.

As a side note, I don't sync any SKUs because it helps with the way my shop reporting works. The current implementation syncs variation SKUs regardless of the settings. 

I'm wondering if we could check whether the setting is on or off and respectively sync or default to the woocommerce default behavior. Any views?

**Comment by Jon007** [comment]
For determining the right behaviour we need to understand the use cases:

If the product is actually different for different languages (different packaging etc) then yes it should have a different SKU and quite possibly separate inventory with different stock levels.

However this concept should not be enforced at site level:  just because the shop has some products with different language packs, it shouldn't be forced to turn off SKU and stock synchronization for all products. 


If the product is different by country then that concept should not be mixed with language, it's actually a different product, examples:
 - the English language product version has different plugs depending on whether it is sold in UK or US:  I don't think we support different products by different locales of the same language
 - the European product has a European plug and can be sold in different language in different European countries (including some which speak English), but should not be sold in UK even if UK English is the primary language.

**Comment by Jon007** [comment]
The main problem I saw with turning off SKU synchronisation is that you then get lots of duplicate SKU warnings which interrupt attempts to save products.   Also if not synchronizing then when adding a new product should the translation SKU be created automatically as main language SKU + language code as suffix?

**Comment by hyyan** [comment]
Fixed in version 1.0.0

**Comment by Jon007** [comment]
Actually you still will get the warnings if you turn off SKU synchronisation on an existing shop, we didn't change that in 1.0.0.

I'm just not quite sure why the warning are there in the first place, whether it matters, or what the correct behaviour should be..

**Comment by hyyan** [comment]
@Jon007 I will double check that

**Comment by Jon007** [comment]
this is fixed with the solution to #313
