### ISSUE TITLE
Wrong Behavior : "my-account/orders/ " show orders according to the current language 

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#75]
Scenario (English , German)

- Buy a product (English)
- checkout (English)
- switch to : my-account/orders/ (English) , you will see orders in English
- switch to : mein-konto/orders/ (German) , you will see orders **No orders**

The expected behavior is to see orders even if they were made using another language

**Comment by rmxs** [comment]
Agree, 
any news about that?

**Comment by decarvalhoaa** [comment]
Thanks for reporting. I have seen this issue since WooCommerce 2.6.0. Unfortunately, WC 2.6. change the way customer orders are fetched from the database and is ignoring the language argument Hyyan plugin adds in.

I have created an issue with WooCommerce <a href="https://github.com/woocommerce/woocommerce/issues/12643" target="_blank">here</a>. I have a fix for that but need some guidance from the WooCommerce folks.

**Comment by decarvalhoaa** [comment]
WooCommerce people come back and decided instead to add a new filter to WP_Query. This will come out with WC 2.7, so until then this bug can't be fixed.

This solution will also force changes to this plugin. The filter name is different but we need also to check whether the `post_type` arg in the query is or contains (if arg is array) 'shop_order'. Otherwise, we will be filtering query for refunds etc that don't have language, therefore returning empty for this queries.

**Comment by decarvalhoaa** [comment]
Fixed via [828d8a03](https://github.com/hyyan/woo-poly-integration/commit/828d8a03db0cc9056300bdcc9b3777bbcc216b34).
