### ISSUE TITLE
Auto Translate Woocommerce Page 

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#78]
@decarvalhoaa  I think it is time to add the Auto Translate Woocommerce Page feature , it is not really hard to add this feature but I was avoiding this because it requires adding more languages support to handle the page names translations , but we can translate names be adding the language slug as a start 

For example : shop -> shop-de and so on ....

**Comment by Jon007** [comment]
I note the main issue may be that Google Translate API is not in fact free (and other translators that are even worse than Google Translate may not be worthwhile), this article explains how to use the API from PHP:
https://www.sitepoint.com/using-google-translate-api-php/

One could at least start by copying over the source language, until an appropriate automated translation is available, eg:
`
// Make sure Polylang copies the title when creating a translation
function hy_editor_title( $title ) {
    // Polylang sets the 'from_post' parameter
    if ( isset( $_GET['from_post'] ) ) {
        $my_post = get_post( $_GET['from_post'] );
        if ( $my_post )
            return $my_post->post_title;
    }

    return $title;
}
add_filter( 'default_title', 'hy_editor_title' );

// Make sure Polylang copies the content when creating a translation
function hy_editor_content( $content ) {
    // Polylang sets the 'from_post' parameter
    if ( isset( $_GET['from_post'] ) ) {
        $my_post = get_post( $_GET['from_post'] );
        if ( $my_post )
            return $my_post->post_content;
    }

    return $content;
}
add_filter( 'default_content', 'hy_editor_content' );

// Make sure Polylang copies the excerpt [woocommerce short description] when creating a translation
function ink_editor_excerpt( $excerpt ) {
    // Polylang sets the 'from_post' parameter
    if ( isset( $_GET['from_post'] ) ) {
        $my_post = get_post( $_GET['from_post'] );
        if ( $my_post )
            return $my_post->post_excerpt;
    }

    return $content;
}
add_filter( 'default_excerpt', 'hy_editor_excerpt' );
`
Of course, it's possible to argue that these are not wooCommerce-specific fields anyway so it's not the scope of this plug-in to do it:  if Polylang did an auto-translate of these core fields, then it would in theory work for wooCommerce too.
The Polylang solution for this is Lingotek, which has both automatic and non-automatic translation (via Lingotek pro translation service), but it was rather inconvenient last time I checked, and the auto-translate was very poor, though they are now switching the service.

**Comment by Jon007** [comment]
fyi I also have some javascript code for the machine translation which I wrote into another plugin, jm-buddy-translate

**Comment by hyyan** [comment]
I will drop this one as this was never an issue for the plugin users, it does not seem there is an optimal solution for now

**Comment by Jon007** [comment]
Well I added the default content stuff above to 1.0.0 anyway.
Separately it would be wise to retest Lingotek:  since Polylang are promoting it, some users will try it.

As far as auto-translation, well I have some ideas and this is the real test:  I can't add languages to my site at the moment without auto-translation, it's just too much work.
I want to:
- Auto-translate from Spanish to Italian, Portuguese and French and then manually correct
- Auto-translate from English to German and assign draft translations to another user.  Our Deutsch ist nicht gut.

So I am imagining a tools page with the options to:

- select Product Category
- select target language
- select status for new Product Translations
- select author to assign for new Product Translations 
- press Translate to fill in missing translations for this Product Category and target language.

*Possibly* this could work via javascript which would be painfully slow, but still a lot faster than going through all the screens manually, using client side solution would also have the following advantages:
- *may* be exempt from licensing issues applying to server solutions as is running as the local user rather than server-side massive translation solution
- can give user feedback and allow interruption by user
