### ISSUE TITLE
Woocommerce Checkout Fails But Emails Are Sent

### ISSUE THREAD

**Issue by hyyan** [hyyan/woo-poly-integration#86]
Woocommerce Checkout Fails And Order Is Not Created  But Emails Are Sent 

The Following Error Is Shown : 

`SyntaxError: Unexpected token < in JSON at position 0`

**Comment by decarvalhoaa** [comment]
I get also this error in the debug logs

`[20-Nov-2016 15:33:19 UTC] PHP Catchable fatal error:  Argument 1 passed to Hyyan\WPI\Product\Stock::change() must be of the type array, object given, called in /var/www/html/tlc-dev/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Stock.php on line 56 and defined in /var/www/html/tlc-dev/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Stock.php on line 90`

**Comment by decarvalhoaa** [comment]
Getting also 

`id|order_date|payment_method|billing_country was called incorrectly. Order properties should not be accessed directly.`

**Comment by decarvalhoaa** [comment]
@hyyan - just that you know, i'm working on this one!

**Comment by Jon007** [comment]
Yes, the specific instances of the error are fixed by the wooCommerce 3.0 fixes, however it's rather worrying that it's possible for this type of situation to occur.

So I'll leave this issue open for a bit more testing to ensure that this cannot reoccur due to future errors:
 - basket is emptied and temporary order is created
 - emails are sent
 - order fails, and now there is no order, no shopping basket.... and maybe soon no customer.

**Comment by hyyan** [comment]
This issue was resolved in version 1.0.0

**Comment by Jon007** [comment]
l think this is still potentially problematic, though maybe is WooCommerce issue as specific WooPoly bug is fixed.
It seemed that in certain situations an error *could* occur where emails are sent but the order is not fully successful.
Ok to close for now, assume structure issue is WooCommerce responsibility and raise new issue if any woo-poly specific problem
