### ISSUE TITLE
support for WC Paid Listings

### ISSUE THREAD

**Issue by saliljnr** [hyyan/woo-poly-integration#9]
Currently, the plugin does not work with Paid Listings variable type of products. Any chance support for this could be added?

**Comment by saliljnr** [comment]
Am still hopeful someone will assist me with this problem. I asked WC Paid Listing author and we went as far as identifying probable source of problem.
This piece of code in /wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Meta.php line-246:

<code>
add_action('save_post', function ($_ID) {
$product = get_product($_ID);
if ($product) {
$type = $product->product_type;
update_post_meta($_ID, '_translation_porduct_type', $type);
}
});
</code>
Apparently on save_post it probably runs before WC Paid Listings plugin has a chance to save anything... So to test, I commented out the function and I could successfully save a Listing Package Subscription :) But when I attempted to translate the product, the translated one still has same issue - Not to mention that obviously commenting out this action call isn't a workable solution in the first place..
Anyone???? I really need this to work!

**Comment by kochhase** [comment]
Hi Saliljnr,
Do you mean WP Job manager Paid Listings plugin?
i have found some solution to translate the slug. https://github.com/KLicheR/wp-polylang-translate-rewrite-slugs. After that i change some slug and i use Polylang 1.8 beta. Now i have translated Paid Listings. But  now see all language packages for each country slug.
Any ideas?

**Comment by Jon007** [comment]
@saliljnr, @kochhase 
Closing as this issue is 2 years old and there are new major versions of Polylang, WooCommerce and this plugin since then.
Please would you let us know if the issue applies on Polylang 2.x, WooCommerce 3.x, woopoly 1.0.3

There is some example for additional custom post meta in the wiki here:
https://github.com/hyyan/woo-poly-integration/wiki/Product-Meta-and-Custom-Fields
but I haven't tested with customized variations.
